### ISSUE TITLE
[Qt6] example程序在界面缩放时存在控件抖动现象

### ISSUE THREAD

**Issue by LiuPeiqiCN** [zhuzichu520/FluentUI#1]
拖动界面时，界面里的控件会存在位置抖动问题，所有界面都有这个问题。
我没有Qt5，但是release发布里v2.3.4的qt5 example程序不存在这个问题。

系统：win11
IDE：VS2022
Qt: v6.4.0

**Comment by zhuzichu520** [comment]
👌🏻这个影响不大，大部分程序都有这个通病，连微信好像也存在。

**Comment by LiuPeiqiCN** [comment]
我描述错误，不是拖动界面，是用鼠标拉伸缩放界面尺寸时，控件位置存在很严重的抖动现象。

**Comment by LiuPeiqiCN** [comment]
升级到6.5.0-rc才解决，6.4.3都不行。
