### ISSUE TITLE
ItemFooter不显示

### ISSUE THREAD

**Issue by scx1125** [zhuzichu520/FluentUI#101]
这是Main.qml代码
`import QtQuick
import QtQuick.Window
import QtQuick.Controls
import QtQuick.Layouts
import Qt.labs.platform
import FluentUI
import "qrc:///demo/"

FluWindow {
    id:window
    width: 1920
    height: 1080
    closeDestory:false
    visible: true
    title: qsTr("映腾网络")
    launchMode: FluWindow.SingleTask
    closeFunc:function(event){
        close_app.open()
        event.accepted = false
    }
    FluContentDialog{
        id:close_app
        title:"映腾网络"
        message:"确定要退出程序吗？"
        negativeText:"最小化"
        buttonFlags: FluContentDialog.NeutralButton | FluContentDialog.NegativeButton | FluContentDialog.PositiveButton
        onNegativeClicked:{
            system_tray.showMessage("友情提示","FluentUI已隐藏至托盘,点击托盘可再次激活窗口");
            window.hide()
        }
        positiveText:"退出"
        neutralText:"取消"
        onPositiveClicked:{
            window.deleteWindow()
            FluApp.closeApp()
        }
    }
    FluNavigationView{
        id:nav_view
        anchors.fill: parent
        title:"映腾网络"
        footerItems: ItemsFooter
        z:11
        displayMode:MainEvent.displayMode
        autoSuggestBox:FluAutoSuggestBox{
            width: 280
            anchors.centerIn: parent
            iconSource: FluentIcons.Search
            placeholderText: "搜索功能"
        }
        actionItem:Item{
            height: 40
            width: 148
            RowLayout{
                anchors.centerIn: parent
                spacing: 5
                FluText{
                    text:"暗黑模式"
                }
                FluToggleSwitch{
                    selected: FluTheme.dark
                    clickFunc:function(){
                        if(FluTheme.dark){
                            FluTheme.darkMode = FluDarkMode.Light
                        }else{
                            FluTheme.darkMode = FluDarkMode.Dark
                        }
                    }
                }
            }
        }
        Component.onCompleted: {
            ItemsFooter.navigationView = nav_view
        }
    }
}
`
这是footer的代码
`pragma Singleton

import QtQuick
import FluentUI

FluObject{

    property var navigationView

    id:footer_items

    FluPaneItemSeparator{}

    FluPaneItem{
        title:"关于"
        icon:FluentIcons.Contact
        tapFunc:function(){
            FluApp.navigate("/about")
        }
    }

    FluPaneItem{
        title:"设置"
        icon:FluentIcons.Settings
        onTap:{
            navigationView.push("qrc:/example/qml/page/T_Settings.qml")
        }
    }

}
`
我在确认编译没有报错的情况下，footer却没有显示出来，

**Comment by zhuzichu520** [comment]
这个ItemsFooter是单例么？如果不是单例的话可以直接写在Main.qml中。
