### ISSUE TITLE
Acrylic效果的替代方案

### ISSUE THREAD

**Issue by mentalfl0w** [zhuzichu520/FluentUI#102]
GitHub上有跨平台（支持Win、Mac、Linux）的[QML解决方案](https://github.com/wangwenx190/qtacrylicmaterial)，效果还不错，局限性也有，不知作为子模块并入FluentUI是否合适？

**Comment by zhuzichu520** [comment]
嗯，可以研究下。我倒是想把这个大佬的无边框作为子模块弄进来。。

**Comment by mentalfl0w** [comment]
我也觉得他的无边框不错，这几天有时间的话在我自己的app里先尝试一下

**Comment by mentalfl0w** [comment]
FramelessHelper的效果不错，但是代码有bug，自动跟随系统切换颜色的模块不稳定，在给出的例子上是正常的，但是在example应用中不正常，我这几天有空就把相关代码提交一下，再去对方仓库提个issue。
<img width="1203" alt="image" src="https://github.com/zhuzichu520/FluentUI/assets/30333935/36a9d550-6574-4712-9d62-a15447416355">
