### ISSUE TITLE
请问 FluArea 如何铺满FluScrollablePage除了标题之外剩下的空间

### ISSUE THREAD

**Issue by satchelwu** [zhuzichu520/FluentUI#107]
目前需要显式地设置高度，FLuArea里面的子控件才能正常的显示，有没有办法让FluArea自动铺满FluScrollablePage剩下的空间呢？

**Comment by zhuzichu520** [comment]
没，如果要铺满FluScrollablePage剩下的空间的话，FluArea的高度肯定是不能让FluScrollablePage出现滚动效果。可以直接用FluContentPage....
