### ISSUE TITLE
请问下当前版本仅支持Qt 6 ？

### ISSUE THREAD

**Issue by parker-int64** [zhuzichu520/FluentUI#11]

**Comment by zhuzichu520** [comment]
main分支已经升级到qt6，还有个qt5的分支。

**Comment by parker-int64** [comment]
> main分支已经升级到qt6，还有个qt5的分支。

是打算用qt6作为长期支持版本？

**Comment by zhuzichu520** [comment]
嗯嗯，目前都在main分支上开发，隔一段时间会同步到Qt5分支。毕竟win7还需要Qt5.15
