### ISSUE TITLE
没有ComboBox组件可以加一个吗

### ISSUE THREAD

**Issue by bShoes** [zhuzichu520/FluentUI#110]
没有ComboBox组件可以加一个吗

**Comment by mentalfl0w** [comment]
有FluComboBox，readme里面没写，但是可以用。

**Comment by zhuzichu520** [comment]
额，FluComboBox里面代码是空的。

**Comment by mentalfl0w** [comment]
> 额，FluComboBox里面代码是空的。

啊不好意思😂，是我记错了，我之前一直是用FluDropDownButton代替的，感觉和ComboBox差不多就记串了。
<img width="564" alt="image" src="https://github.com/zhuzichu520/FluentUI/assets/30333935/4402e731-605a-4bb6-b329-557c1820298d">

**Comment by zhuzichu520** [comment]
我也觉得和FluDropDownButton，FluMenu差不多。但是我想把这个用Window封装一个，可以在窗口外面。FluDropDownButton和FluMenu都只能在窗口内。。

**Comment by funeetop** [comment]
FluDropDownButton 可以支持类似ComboBox对CPP/JS List Model data的支持吗

**Comment by zhuzichu520** [comment]
已经添加FluComboBox。它继承了ComboBox~，支持ListModel

**Comment by zhuzichu520** [comment]
已经添加FluComboBox。它继承了ComboBox~，支持ListModel
