### ISSUE TITLE
Linux下遇见的问题

### ISSUE THREAD

**Issue by Met4physics** [zhuzichu520/FluentUI#115]

**Comment by Met4physics** [comment]
18:12:44: Starting /home/met4physics/Desktop/Fluent/FluentUI-1.3.0/bin/debug/example...
QML debugging is enabled. Only use this in a safe environment.
Our global IPC ID is  17073988307340140698
QQmlApplicationEngine failed to load component
qrc:/example/qml/App.qml:5:1: module "FluentUI" plugin "fluentuiplugin" not found
linux编译没有问题，运行example出现这种问题，qml文件夹下存在fluentuiplugin.qmltypes。
qt为6.4.3，fluent1.3.0版本

**Comment by zhuzichu520** [comment]
-DCMAKE_PREFIX_PATH=<YOUR_QT_SDK_DIR_PATH

编译的时候加了CMAKE_PREFIX_PATH没？

**Comment by Met4physics** [comment]
我使用qt creator，CMAKE_PREFIX_PATH设置为-DCMAKE_PREFIX_PATH:PATH=/home/met4physics/Qt/6.4.3/gcc_64，应该没有问题。同时windows上运行没有出错

**Comment by Met4physics** [comment]
![image](https://github.com/zhuzichu520/FluentUI/assets/91643087/60ae42c1-39c8-4965-a876-9e91c58c1b9c)

**Comment by Met4physics** [comment]
这是linux下qml/FluentUI文件夹里的，似乎比windows少了东西？

**Comment by Met4physics** [comment]
1.2.9能够成功运行。
