### ISSUE TITLE
#新手入门起步问题

### ISSUE THREAD

**Issue by SanMaoInt0x3** [zhuzichu520/FluentUI#117]
问题1：我是mfc electron 选手，跟着 wiki 入门教程里编译无法运行example，环境是 msvc 2019 x64   qtcreater 10。报错在 ：component/CustomWindow.qml。
问题2：跟着Demo能运行起来，但是 FluWindow 所创建的窗口任然有边框。

![8ZPZRNGTAE$1M3R87H {S7R](https://github.com/zhuzichu520/FluentUI/assets/127284864/e060edb8-9eb7-4b6c-89be-4a3cbbbe6b16)

![image](https://github.com/zhuzichu520/FluentUI/assets/127284864/d37fac65-3c6c-406e-b32c-c9404fd3abce)

**Comment by zhuzichu520** [comment]
FluWindow并没有提供无边框。example中是用framelesshelper的无边框库。代码中多了一个A
![1684638435008](https://github.com/zhuzichu520/FluentUI/assets/56627161/5b244305-e086-4fe3-bad6-8466b0c74979)

**Comment by SanMaoInt0x3** [comment]
> FluWindow并没有提供无边框。example中是用framelesshelper的无边框库。代码中多了一个A ![1684638435008](https://user-images.githubusercontent.com/56627161/239717948-5b244305-e086-4fe3-bad6-8466b0c74979.png)

谢谢答疑
