### ISSUE TITLE
main分支现在不能运行吗？

### ISSUE THREAD

**Issue by mxdlzg** [zhuzichu520/FluentUI#143]
## 环境
Win11
Qt 6.4.3
FluentUI 1.3.1

## 问题
最新的代码，编译没问题，运行会报错：
QQmlComponent: Component is not ready
ASSERT: "state.creator" in file \Users\qt\work\qt\qtdeclarative\src\qml\qml\qqmlcomponent.cpp, line 312

![image](https://github.com/zhuzichu520/FluentUI/assets/18144577/a899dc90-2b12-4005-a289-d67ca3515d92)

**Comment by zhuzichu520** [comment]
![image](https://github.com/zhuzichu520/FluentUI/assets/56627161/f1ea74be-6a50-4dd8-ba5b-e66051b995d7)
可以运行的

**Comment by mxdlzg** [comment]
> ![image](https://user-images.githubusercontent.com/56627161/242199393-f1ea74be-6a50-4dd8-ba5b-e66051b995d7.png) 可以运行的

单纯添加控件的确没问题，但是example那个demo跑不了，跟上面那个错误是一样的。所以我想复制example的代码到这个hello world中，结果还是一样的错误。

是那个example实现的比较特殊吗？

**Comment by zhuzichu520** [comment]
额，可能是哪里漏掉没复制过去，导致qml加载异常错误了

**Comment by mxdlzg** [comment]
> 

大致可以复现问题了，但是原因还是不知道。比如最简单的配置一个window：

![image](https://github.com/zhuzichu520/FluentUI/assets/18144577/525df45e-8def-4bfb-be51-0824287f01bc)

然后MainWindow.qml是这样：

![image](https://github.com/zhuzichu520/FluentUI/assets/18144577/55a1f702-6258-43ac-b48b-a609ea6a8ae8)

然后稳定崩溃：

![image](https://github.com/zhuzichu520/FluentUI/assets/18144577/f9e2e6a0-c0d1-4747-9c31-53796a30f00f)

**Comment by zhuzichu520** [comment]
qrc:/MainWindow.qml 这个资源路径是对的么？

**Comment by mxdlzg** [comment]
> qrc:/MainWindow.qml

跟Main.qml是同级的，按说不写qrc应该也行吧？但是现在带不带都不行，甚至不写具体qml也报错，比如这样：
![image](https://github.com/zhuzichu520/FluentUI/assets/18144577/b305b8e9-beb8-4e25-9d37-a518432a1320)

**Comment by zhuzichu520** [comment]
同级是同级，看下你的CmakeList.text 有没有把资源添加进去

**Comment by mxdlzg** [comment]
> 看下你的CmakeList.txt 有没有把资源添加进去。还有每次添加新的资源，需要重新执行一下cmake。 ![1685528305763](https://user-images.githubusercontent.com/56627161/242242091-14d080d4-1aff-4938-88ce-c7980ad183ae.png)

加了的。。。我服了，这究竟是为什么。
![image](https://github.com/zhuzichu520/FluentUI/assets/18144577/23e5c3a9-a25f-43f0-bb35-ae2c47acbf65)


**关键关键是，为什么弄个小demo验证，就是因为main分支上直接qt creator构建运行，就报这个错误。**

**Comment by mxdlzg** [comment]
@zhuzichu520 问题解决，至于为啥不行，还是不清楚，我关问题了吧。

**或许是main分支还不是完全QT6的吗？**


方案：
安装Qt5 compatible components就可以了

_Originally posted by @scx1125 in https://github.com/zhuzichu520/FluentUI/issues/86#issuecomment-1546589101_

**Comment by lingkerio** [comment]
我安装了Qt5 compatible module但还是报这个一模一样的错，这是为什么

**Comment by lingkerio** [comment]
不过DEMO我是可以跑的，可能是我自己代码问题
