### ISSUE TITLE
源码单词写错了

### ISSUE THREAD

**Issue by cworld1** [zhuzichu520/FluentUI#147]
嗯... 没有文档就只能啃源代码去了，一边啃一边就发现了这个。

文件 [FluTableView](https://github.com/zhuzichu520/FluentUI/blob/main/src/imports/FluentUI/Controls/FluTableView.qml) 有好几处的单词 `columns` 写成了 `coumns`。例图：

![image](https://github.com/zhuzichu520/FluentUI/assets/37377181/992c72e7-3bb4-487b-8e1f-ef000f3a2682)

部分位置：

https://github.com/zhuzichu520/FluentUI/blob/5af755dd9579b58d2b60684839de692133ca508e/src/imports/FluentUI/Controls/FluTableView.qml#L66

https://github.com/zhuzichu520/FluentUI/blob/5af755dd9579b58d2b60684839de692133ca508e/src/imports/FluentUI/Controls/FluTableView.qml#L33

**Comment by cworld1** [comment]
另外想问下代码：

```qml
navigationView.push("qrc:/fluentmail/qml/page/T_Home.qml")
```

怎么实现在任意想要的页面使用/正常执行，以及这个函数实现上能不能额外加参数。没有找到源代码（痛）

**Comment by zhuzichu520** [comment]
单词已经修改。push方法新增第二个参数argment。
https://github.com/zhuzichu520/FluentUI/blob/1073efe423100cd60e63905b43e56415c739b49c/src/imports/FluentUI/Controls/FluNavigationView.qml#L899

**Comment by cworld1** [comment]
额外参数已经可以正常使用了，非常感谢。另外我想表达似乎没法从 `ItemsOriginal` 和 `ItemsFooter` 以外的文件使用这个函数 `navigationView.push`，不知道是不是我方法不对。

**Comment by cworld1** [comment]
嗯...作者没有这方面考虑么？如果没有我就关掉了，已经没有很明显的这方面需求了。不过在此感谢作者奉献，整个库封装的真的很好用🥰
