### ISSUE TITLE
[Help Wanted] Qt 6.5.0 无法通过编译

### ISSUE THREAD

**Issue by Hatsushigure** [zhuzichu520/FluentUI#148]
如图
![image](https://github.com/zhuzichu520/FluentUI/assets/65275829/25c29022-38f1-4e32-b829-7d0c22f6dc10)

**Comment by Hatsushigure** [comment]
建议不要用 `_p` 结尾的文件, 里面的内容可能随时更改

**Comment by zhuzichu520** [comment]
嗯，用到了private里面的api获取系统的主题是否是深色模式，还不知道有啥方法可以替代的。。

**Comment by Hatsushigure** [comment]
试一下 `QPalette`?(我没试过)

**Comment by Hatsushigure** [comment]
找到了 Qt 官方给的方案(Qt 6.5)
https://www.qt.io/blog/dark-mode-on-windows-11-with-qt-6.5#:~:text=Qt%206.5%20Way

**Comment by Hatsushigure** [comment]
建议把 Qt 升级到 6.5, 毕竟 6.5 才是 LTS, 未来用的人可能会多一些

**Comment by zhuzichu520** [comment]
1.3.2已经修改，mian分支已经升级到Qt6.5
