### ISSUE TITLE
QQmlComponent: Component is not ready

### ISSUE THREAD

**Issue by satchelwu** [zhuzichu520/FluentUI#149]
编译完成运行程序，提示：
QQmlComponent: Component is not ready
ASSERT: "state.creator" in file \Users\qt\work\qt\qtdeclarative\src\qml\qml\qqmlcomponent.cpp, line 312

![image](https://github.com/zhuzichu520/FluentUI/assets/6259509/7ed7bbc5-1955-4de2-a9cf-c01c2cae0406)
![image](https://github.com/zhuzichu520/FluentUI/assets/6259509/0d90bed2-9b86-4797-af69-7ccf0706ae2d)

`const QUrl url(QStringLiteral("qrc:/res/qml/App.qml"));`
![image](https://github.com/zhuzichu520/FluentUI/assets/6259509/1f9d83dd-f77d-435f-bc25-7e1d19c1566a)
![image](https://github.com/zhuzichu520/FluentUI/assets/6259509/3632fa98-13bb-4b7b-86b5-2f509aa52c66)

请问可能是什么原因呢？

**Comment by zhuzichu520** [comment]
安装的时候勾选Qt 5 Compatibility Module
![1685951863847](https://github.com/zhuzichu520/FluentUI/assets/56627161/76298b19-656b-41ac-9967-0822a3bf960e)

**Comment by satchelwu** [comment]
@zhuzichu520 安装了的，突然就不行了，我重新试了一个test project，问题仍然存在
[TestProject.zip](https://github.com/zhuzichu520/FluentUI/files/11652718/TestProject.zip)

**Comment by satchelwu** [comment]
我再FluentUI example 工程里面屏蔽了关于FramelessHelper的相关的，编译运行就会报同样的错误

**Comment by satchelwu** [comment]
up主，麻烦有空帮看看，谢谢

**Comment by lingkerio** [comment]
请问有解决这个问题吗？我也是一模一样的问题...

**Comment by tianxiaofan** [comment]
![image](https://github.com/zhuzichu520/FluentUI/assets/31602999/c60d950f-43e3-45d9-bae4-a3bd6d3b0bb1)
我的是这样的报错，Qt版本为6.5.1。查后发现src下的CMakeList.txt会设置FluentUI进入Qt库目录：
![image](https://github.com/zhuzichu520/FluentUI/assets/31602999/e9e56feb-fa2a-4a7b-88ee-947728eae4fc)
Qt官方qml目录下的FluentUI删除后，重新生成就OK了
