### ISSUE TITLE
Qt Creater编译失败

### ISSUE THREAD

**Issue by xluu233** [zhuzichu520/FluentUI#15]
环境：
win11
qt creator 9.0.2
编译套件 qt 6.4.2   mingw64bit

FluentUI可以正常编译，但是example编译报错，请教下大佬是什么原因...
![image](https://user-images.githubusercontent.com/36953440/229551521-81539dfe-0e5b-42e4-9257-72a103121cf1.png)

**Comment by xluu233** [comment]
图一问题已解决，原来是没添加multimedia组件库

但是又有一个编译问题：
![image](https://user-images.githubusercontent.com/36953440/229554981-bbb27635-8553-4e5b-82bc-e83245832750.png)

**Comment by zhuzichu520** [comment]
嗯，路径复制dll的路径分隔符有问题，再拉下main代码看看
