### ISSUE TITLE
navigation view 怎么不用stack的方式呢？

### ISSUE THREAD

**Issue by satchelwu** [zhuzichu520/FluentUI#154]
点击就新建的话，会有很多重复的界面

**Comment by zhuzichu520** [comment]
可以把FluScrollablePage、FluContentPage的pageMode属性设置为FluNavigationView.SingleTask。比如T_Home页面设置了这个属性，就会看栈中有没有T_Home页，如果有的话就不会创建新的页面，而是把T_Home上面的页面全部pop掉。
https://github.com/zhuzichu520/FluentUI/blob/2cfd5b3ab221b5ecf06cf6ce2d0ccff811d48c70/example/qml/page/T_Home.qml#L10

**Comment by satchelwu** [comment]
ack，多谢up主
