### ISSUE TITLE
在macos 13.4 arm64，使用brew安装的qt6.5.1环境下编译报错：

### ISSUE THREAD

**Issue by gitcsw** [zhuzichu520/FluentUI#161]
在macos 13.4 arm64，使用brew安装的qt6.5.1环境下：
cmake -DCMAKE_PREFIX_PATH=/opt/homebrew  -DCMAKE_BUILD_TYPE=Release -GNinja /Users/xxx/Documents/projs/FluentUI
cmake --build . --config Release --target all --parallel
报错：
...
[218/354] Linking CXX shared library /...w/qml/FluentUI/libfluentuiplugin.dylib
FAILED: /opt/homebrew/qml/FluentUI/libfluentuiplugin.dylib 
: && /Library/Developer/CommandLineTools/usr/bin/c++ -O3 -DNDEBUG -arch arm64 -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk......
-framework DiskArbitration && :
ld: warning: ignoring file /opt/homebrew/lib/QtQuick.framework/Versions/A/QtQuick, building for macOS-x86_64 but attempting to link with file built for macOS-arm64ld: warning: ignoring file /opt/homebrew/lib/QtGui.framework/Versions/A/QtGui, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /opt/homebrew/lib/QtOpenGL.framework/Versions/A/QtOpenGL, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
Undefined symbols for architecture x86_64:
  "qErrnoWarning(char const*, ...)", referenced from:
      FluApp::navigate(QString const&, QJsonObject const&, FluRegister*) in FluApp.cpp.o
  "qmlRegisterModule(char const*, int, int)", referenced from:
      qml_register_types_FluentUI() in fluentuiplugin_qmltyperegistrations.cpp.o
  "qRegisterResourceData(int, unsigned char const*, unsigned char const*, unsigned char const*)", referenced from:
      qInitResources_qmake_FluentUI() in qrc_qmake_FluentUI.cpp.o
      __GLOBAL__sub_I_qrc_qmake_FluentUI.cpp in qrc_qmake_FluentUI.cpp.o
...
ninja: build stopped: subcommand failed.
虽然初步判断可能是x86和arm64问题，但是我对cmake并不熟，望有经验的大佬指点一二～

**Comment by parker-int64** [comment]
加个`-DCMAKE_OSX_ARCHITECTURES=arm64`试试？

**Comment by mentalfl0w** [comment]
确认一下你的brew安装的Qt是什么架构的，是否包含arm64的库，我看日志里面有出现错误链接不同架构动态库的情况，建议直接使用Qt Online Installer安装。

**Comment by gitcsw** [comment]
发现确实是brew安装的缘故，Qt Online Installer安装的6.2.4版本编译没有出现上述架构问题。不过源代码报错，估计c++语法关系，待研究后若仍未解决开新的issue。
