### ISSUE TITLE
qml如何打包发布

### ISSUE THREAD

**Issue by qq1972474341** [zhuzichu520/FluentUI#162]
如何打包发布  qml打包  但是会提示组件未加载

**Comment by qq1972474341** [comment]
QQmlComponent: Component is not ready

**Comment by zhuzichu520** [comment]
qml打包要添加--qmldir <你的项目路径>

**Comment by qq1972474341** [comment]
带上了  但是运行不起来 我用Qt在目录下运行提示QQmlComponent: Component is not ready  。 但是前面调试是没这个问题的

**Comment by qq1972474341** [comment]
> qml打包要添加--qmldir <你的项目路径>

FluNavigationView  的logo 打包后没带上是什么原因呢

**Comment by qq1972474341** [comment]
qrc路径下的资源不会打包带上吗

**Comment by qq1972474341** [comment]
已解决 感谢~

**Comment by big-show** [comment]
自己之前做的，最早是直接在example改的，现在发布遇到一些问题，使用这个命令发布，windeplyqt --qmldir E:\QTest\A1  E:\QTest\out\A1.exe 
那个qmldir指定的路径，是example的路径，还是FluentUI的路径，还是哪个路径？现在example就是我的项目，请大佬解答

**Comment by big-show** [comment]
> 自己之前做的，最早是直接在example改的，现在发布遇到一些问题，使用这个命令发布，windeplyqt --qmldir E:\QTest\A1  E:\QTest\out\A1.exe
> 那个qmldir指定的路径，是example的路径，还是FluentUI的路径，还是哪个路径？现在example就是我的项目，请大佬解答

**Comment by big-show** [comment]
> 已解决 感谢~

自己之前做的，最早是直接在example改的，现在发布遇到一些问题，使用这个命令发布，windeplyqt --qmldir E:\QTest\A1  E:\QTest\out\A1.exe
那个qmldir指定的路径，是example的路径，还是FluentUI的路径，还是哪个路径？现在example就是我的项目，请大佬解答
