### ISSUE TITLE
新版FluTableView不支持Lazy Load

### ISSUE THREAD

**Issue by mentalfl0w** [zhuzichu520/FluentUI#169]
新版的FluTableView需要一次性加载全部的数据，但实际上如果需要存放的数据非常多，没有办法一次性全部让服务器返回，给用户的体验不好，原本的FluTableView是可以Lazy Load的，用户需要哪一页的数据再加载哪一页即可，现在得全部加载属实不方便了，而且`TableView.editDelegate`和`TableView.onCommit`是Qt 6.5才支持的，Qt 6.2用不了。

**Comment by zhuzichu520** [comment]
嗯，现在把FluPagination拆出来使用，可以在FluTableView下面放一个FluPagination。TableView.editDelegate与TableView.editDelegate我再兼容一下

**Comment by zhuzichu520** [comment]
1.3.6.2可以再看看。

**Comment by mentalfl0w** [comment]
<img width="944" alt="image" src="https://github.com/zhuzichu520/FluentUI/assets/30333935/3a254694-7f8a-49e2-a574-5fa48506813d">
好像还是有点bug，current和selected没有被赋值

**Comment by mentalfl0w** [comment]
问题解决

**Comment by zhuzichu520** [comment]
1.3.7.0已添加这个功能

**Comment by mentalfl0w** [comment]
目前测试大部分功能正常，但还有一个小bug，双击表格项目，里面的编辑框位置会上移，同时因为表格行高限制，有些长信息显示不全，是否加一个Tooltip会比较合适？ 
<img width="124" alt="image" src="https://github.com/zhuzichu520/FluentUI/assets/30333935/aa2e7f8e-a34d-450f-a17f-02a50de81ede">

**Comment by mentalfl0w** [comment]
> 目前测试大部分功能正常，但还有一个小bug，双击表格项目，里面的编辑框位置会上移，同时因为表格行高限制，有些长信息显示不全，是否加一个Tooltip会比较合适？ <img alt="image" width="124" src="https://user-images.githubusercontent.com/30333935/249530327-aa2e7f8e-a34d-450f-a17f-02a50de81ede.png">

测试发现是因为默认设置的height太小了，height不能小于40左右才行，不能不设置默认值

**Comment by mentalfl0w** [comment]
> 目前测试大部分功能正常，但还有一个小bug，双击表格项目，里面的编辑框位置会上移，同时因为表格行高限制，有些长信息显示不全，是否加一个Tooltip会比较合适？ <img alt="image" width="124" src="https://user-images.githubusercontent.com/30333935/249530327-aa2e7f8e-a34d-450f-a17f-02a50de81ede.png">

已由 #174 解决。
