### ISSUE TITLE
鼠标悬浮/点击区域不准确

### ISSUE THREAD

**Issue by Leezheng1** [zhuzichu520/FluentUI#17]
你好，体验了一下Example，FluentUI 实现的非常棒，对于qml刚入门的我有很大的帮助，非常感谢你的开源项目。

系统型号：windows 10 ThinkCenter
FluentUI Example 版本：1.1.9

在我体验过程中，遇到点问题，希望对产品的优化有帮助：

左侧导航栏及所有的按钮，鼠标影响区域都不准确。
1、左侧导航栏：
1.1  经常遇到鼠标在导航栏上，却无法点击。
1.2  点击某个导航栏 经常会错误的响应到相邻的导航栏按钮。比方说我鼠标在 TimePicker 上，但是点击后却响应了DatePicker

2、按钮：
2.1 所有按钮影响位置感觉都偏上，鼠标需要点击在按钮的top位置 偏上一点才可以响应
2.2  Basic input -> Buttons  右侧的Disabled 按钮，经常会点击不到 （尤其是  Standard Button）。我需要把鼠标放在这个Disabled Btn的很靠上的位置，才可以响应我的操作。

**Comment by zhuzichu520** [comment]
感谢你的反馈，按钮的hovered效果触发了没，我这边还是很好点击的。可能渲染出问题了，可以尝试拉伸一下窗口改变一下窗口的宽高，让窗口重绘一下。

**Comment by zhuzichu520** [comment]
我想想是什么原因会导致渲染错位了。。

**Comment by Leezheng1** [comment]
> 感谢你的反馈，按钮的hovered效果触发了没，我这边还是很好点击的。可能渲染出问题了，可以尝试拉伸一下窗口改变一下窗口的宽高，让窗口重绘一下。

之前遇到的问题：
1、Btn 的hovered  效果需要在按键的 top 位置 之上才能触发
2、导航栏经常会 没有hoverd 效果

我退出程序，重新启动了一下，已经没有问题了。
