### ISSUE TITLE
加入了FramelessHelper之后，启动程序多出来1个小窗口

### ISSUE THREAD

**Issue by satchelwu** [zhuzichu520/FluentUI#175]
![image](https://github.com/zhuzichu520/FluentUI/assets/6259509/3b7bf549-ebb2-4286-8936-e629b6083831)
up主知道这个窗口怎么多出来的吗？

**Comment by zhuzichu520** [comment]
这应该是个初始化窗口，你的第一个窗口是不是设置了visible:true

**Comment by satchelwu** [comment]
App.qml 中的Window 确实设置了，刚屏蔽了，果然没有了，多谢up主
