### ISSUE TITLE
必须得6.4.3吗？

### ISSUE THREAD

**Issue by sunqian119** [zhuzichu520/FluentUI#177]
![1.png](https://github.com/zhuzichu520/FluentUI/assets/40993130/d807d71b-4b8d-435c-9087-9f85bf39b792)

![2.png](https://github.com/zhuzichu520/FluentUI/assets/40993130/bf1ea980-a49c-4805-9b39-0191458b04f0)

![3.png](https://github.com/zhuzichu520/FluentUI/assets/40993130/adebd904-1e0f-4d54-9296-5f8b34e5d0ed)

拉取最新的代码，初次编译。

**Comment by zhuzichu520** [comment]
换6.2.4、6.4.3、6.5.0试试。我一般是在这三个版本开发的。

**Comment by sunqian119** [comment]
> 换6.2.4、6.4.3、6.5.0试试。我一般是在这三个版本开发的。这个三个版本是LTS版，最好还是用这三个版本

6.5.1编译成功，运行OK。就是编译期间，上图的warning还在。😄

**Comment by yanhuacuo** [comment]
Qt6 中，QCreator 如果出现 warning，但编译正常，退出，删掉编译物和 cmakelist.user，重新打开就可以。
QCreator 有问题。
