### ISSUE TITLE
Qt5 分支编译

### ISSUE THREAD

**Issue by Tncent** [zhuzichu520/FluentUI#187]
src编译后报错在  $$[QT_INSTALL_QML]/FluentUI 下也未生成 
QT_VERSION: 5.12.12

**Comment by mentalfl0w** [comment]
可以尝试一下我的实验性分支 #184

**Comment by Tncent** [comment]
CMake配置出错了 QAQ 在QT 5.12.12中编译不通过 @mentalfl0w

**Comment by mentalfl0w** [comment]
> CMake配置出错了 QAQ 在QT 5.12.12中编译不通过 @mentalfl0w

报错是什么方便贴一下图吗？

**Comment by Tncent** [comment]
![图片](https://img1.imgtp.com/2023/07/10/QEQv60VF.png) 

QT_VERSION : 5.12.12

**Comment by mentalfl0w** [comment]
> ![图片](https://camo.githubusercontent.com/490bd77fede6ae43cf42c8e09a52adf841a396693a9b5f3cfdf4eed6aa02c7e6/68747470733a2f2f696d67312e696d6774702e636f6d2f323032332f30372f31302f51455176363056462e706e67)
> 
> QT_VERSION : 5.12.12

应该是不支持Qt 5.15.2以下的版本了。

**Comment by Tncent** [comment]
好吧，我尝试去换个QT版本
