### ISSUE TITLE
求助！ FluDropDownButton items

### ISSUE THREAD

**Issue by yuanlei88** [zhuzichu520/FluentUI#190]
我根据example  Items:[] 提示不存在items成员

**Comment by zhuzichu520** [comment]
额，那个代码案例有问题，items属性已经删掉了，你可以把FluMenuItem写到FluDropDownButton的子项里面。

**Comment by zhuzichu520** [comment]
```
FluDropDownButton{
            disabled:drop_down_button_switch.checked
            text:"DropDownButton"
            anchors{
                verticalCenter: parent.verticalCenter
                left: parent.left
            }
            FluMenuItem{
                text:"Menu_1"
            }
            FluMenuItem{
                text:"Menu_2"
            }
            FluMenuItem{
                text:"Menu_3"
            }
            FluMenuItem{
                text:"Menu_4"
                onClicked: {
                    console.debug(parent.height)
                }
            }
        }
```

**Comment by yuanlei88** [comment]
谢谢您的回复。我在您的组件的onclicked中也看到了items。是不是也需要修改？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月7日(周五) 下午4:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhuzichu520/FluentUI] 求助！ FluDropDownButton items (Issue #190)




 FluDropDownButton{             disabled:drop_down_button_switch.checked             text:"DropDownButton"             anchors{                 verticalCenter: parent.verticalCenter                 left: parent.left             }             FluMenuItem{                 text:"Menu_1"             }             FluMenuItem{                 text:"Menu_2"             }             FluMenuItem{                 text:"Menu_3"             }             FluMenuItem{                 text:"Menu_4"                 onClicked: {                     console.debug(parent.height)                 }             }         }

**Comment by zhuzichu520** [comment]
嗯嗯，那个items没用，已经删掉。。
