### ISSUE TITLE
FluTableView内容显示不全或者最后一个中文字符换行

### ISSUE THREAD

**Issue by MilesGO517** [zhuzichu520/FluentUI#196]
![1](https://github.com/zhuzichu520/FluentUI/assets/48858859/39762e7c-eb7f-40b8-b353-20039cf2e9fa)

如果是英文和数字就显示不全，如果是中文就总是在最后一个字换行

**Comment by zhuzichu520** [comment]
这是哪个分支的？

**Comment by zhuzichu520** [comment]
看着像是qt5。那个分支落后太多了。换到qt-5.15.2分支

**Comment by MilesGO517** [comment]
使用qt-5.15.2分支正常了

**Comment by 13477001653** [comment]
> 使用qt-5.15.2分支正常了
你好能请教下怎么使用吗，我的显示不出来![image](https://github.com/zhuzichu520/FluentUI/assets/69187939/859789eb-42d2-47dd-87fd-21c9dd9d4ae9)
