### ISSUE TITLE
Qt5.15移植最新版之后图像显示大小与最新版不同

### ISSUE THREAD

**Issue by OctalZero** [zhuzichu520/FluentUI#20]
移植版：
![image](https://user-images.githubusercontent.com/75478802/230071315-e986f0a6-7e60-47df-acde-c53cf46ff45e.png)
最新版：
![image](https://user-images.githubusercontent.com/75478802/230071250-514019ec-0757-4308-9caf-3d3c7c2de239.png)
请问如何解决呢？原版显示太小了。

**Comment by zhuzichu520** [comment]
main函数中添加QCoreApplication::setAttribute(Qt::AA_EnableHighDpiScaling);，Qt6中默认支持的

**Comment by OctalZero** [comment]
> main函数中添加QCoreApplication::setAttribute(Qt::AA_EnableHighDpiScaling);，Qt6中默认支持的
和您原来贴的首页显示效果一样，字体很小。
![image](https://user-images.githubusercontent.com/75478802/230098678-fba9592b-34ef-4675-a19f-524568583f49.png)

**Comment by OctalZero** [comment]
已经解决了，谢谢博主帮我定位了问题所在，我在Qt5.15中添加如下代码解决了显示的问题
#ifdef Q_OS_WIN32
  QCoreApplication::setAttribute(Qt::AA_EnableHighDpiScaling);
  QCoreApplication::setAttribute(Qt::AA_UseHighDpiPixmaps);
  QGuiApplication::setHighDpiScaleFactorRoundingPolicy(Qt::HighDpiScaleFactorRoundingPolicy::PassThrough);
#endif

**Comment by zhuzichu520** [comment]
强！
