### ISSUE TITLE
release1.3.7.4_Qt6.5.0,窗体透明bug

### ISSUE THREAD

**Issue by 1821746019** [zhuzichu520/FluentUI#208]
# 测试平台: win10 22H2
# 问题: 右侧,下方,整体意外透明
## 正常
![透明bug_正常](https://github.com/zhuzichu520/FluentUI/assets/107804044/20019f7c-0371-4280-86b0-1bea4a47cad4)
## 向右拉大窗体
![透明bug_有问题_](https://github.com/zhuzichu520/FluentUI/assets/107804044/6b67db90-4dc9-4acd-835f-1383e8451874)
## 最大化
![透明bug_全屏](https://github.com/zhuzichu520/FluentUI/assets/107804044/4bdb5f53-b634-44c5-83dc-71f4f83b3aa2)
## 窗体拖动到屏幕外
![透明bug_拖动](https://github.com/zhuzichu520/FluentUI/assets/107804044/21749a2c-b8dd-483a-a8dd-1cbd20cc44bd)

**Comment by 1821746019** [comment]
作者是没看到吗?最新版本我试了下,mingw和msvc编译的都试了,bug同样存在.

**Comment by liangyuR** [comment]
我这边看了下 1.5.3 没有复现这个bug

**Comment by 1821746019** [comment]
1.5.3版本确实是修复了,这下终于可以放心用了🥰.
![uTools_1692630097062](https://github.com/zhuzichu520/FluentUI/assets/107804044/16578825-15bc-431c-bc13-b8ab2f5aa6dc)
