### ISSUE TITLE
FluDatePicker中可以修改弹出的下拉框的样式吗

### ISSUE THREAD

**Issue by mengyou1024** [zhuzichu520/FluentUI#215]
我想要在FluDatePicker中可以修改弹出的下拉框的样式，比如修改按钮颜色圆角等等，应该怎么办？

**Comment by FeJQ** [comment]
@zhuzichu520 我的问题也类似, 想改变FluPaneItemSeparator的anchors.margin, 
![image](https://github.com/zhuzichu520/FluentUI/assets/41857119/ff4c7b2d-91bd-4ed5-b572-27cb6016e829)

**Comment by FeJQ** [comment]
还是html css好啊,  人家ui的属性都是透明的, 随便改
