### ISSUE TITLE
Qt6.4.1 MSVC2019 x64编译问题

### ISSUE THREAD

**Issue by Edassap** [zhuzichu520/FluentUI#218]
可以正常编译FluentUI库，但build_example 为 ON时，无法通过编译。配置如标题，问题如下图请大佬指导下，不胜感激。
![image](https://github.com/zhuzichu520/FluentUI/assets/16076576/638da026-d612-49c5-8241-9f77d36ed8f1)

**Comment by zhuzichu520** [comment]
用6.4.3或者6.5.0试试。。
