### ISSUE TITLE
FluHttpInterceptor is not a type

### ISSUE THREAD

**Issue by Crjj** [zhuzichu520/FluentUI#219]
QML debugging is enabled. Only use this in a safe environment.
QQmlApplicationEngine failed to load component
qrc:/example/qml/App.qml:11:5: FluHttpInterceptor is not a type
10:28:09: F:\git\FluentUI\bin\debug\example.exe 
编译未出现错误，运行出现该提示，环境qt6.5.0  msvc2019 64bit
请教下哪个环节没配置到位

Window {
    id: app
    flags: Qt.SplashScreen

    FluHttpInterceptor{
        id:interceptor
        function onIntercept(request){
            if(request.method === "get"){
                request.params["method"] = "get"
            }
            if(request.method === "post"){
                request.params["method"] = "post"
            }
            request.headers["token"] ="yyds"
            request.headers["os"] ="pc"
            console.debug(JSON.stringify(request))
            return request
        }
    }
   ...............

**Comment by zhuzichu520** [comment]
清一下缓存，重新rebuild一下

**Comment by Crjj** [comment]
切换release模式编译即可，感谢大佬

**Comment by Crjj** [comment]
> 清一下缓存，重新rebuild一下

切换release模式编译即可，感谢大佬
