### ISSUE TITLE
在macOS 13.4.1中一直编译不成功

### ISSUE THREAD

**Issue by racall** [zhuzichu520/FluentUI#221]
<img width="1719" alt="image" src="https://github.com/zhuzichu520/FluentUI/assets/12036286/ba62aa75-5cfe-4b77-90a5-1ccd902086e3">
无论是Qt Creater还是命令编译，都提示:
ninja: build stopped: subcommand failed.

**Comment by racall** [comment]
debug和release模式都试过了

**Comment by zixianweei** [comment]
可以试试下面的步骤：

1. 在终端里输入下面的命令看是否能够找到`ninja`命令，如果找不到可以尝试使用`brew install ninja`安装一下`ninja`：

```shell
ninja --version
```

2. 如果能够在终端中找到`ninja`，但是无法在Qt Creator中使用，可以尝试在终端中运行下面的命令启动Qt Creator，而不是直接双击图标启动Qt Creator:

```shell
# 具体的路径取决于QtCreator的安装路径
/Applications/Qt\ Creator.app/Contents/MacOS/Qt\ Creator
```

**Comment by racall** [comment]
@zixianweei   我clone main分支最新的无法编译，然后切换到tag 1.3.7.3，编译成功了。我下载最新的[example_1.3.7.4_macos-12_Qt6.5.0.dmg](https://github.com/zhuzichu520/FluentUI/releases/download/1.3.7.4/example_1.3.7.4_macos-12_Qt6.5.0.dmg). 会崩溃

**Comment by mentalfl0w** [comment]
建议使用Qt Online Install而不是homebrew安装的版本来编译。Homebrew安装的Qt不支持Universal构建，而FluentUI默认是开启Universal构建的。

**Comment by racall** [comment]
@zixianweei   main分支编译不过，报错就是截图的那个，往上面查找只有一些警告，没有error部分。我有时间在试试看

**Comment by racall** [comment]
@mentalfl0w   我就是用Qt Online Installer安装的QT，我的QT版本是6.4.3，报错就是截图的那个，往上面查找只有一些警告，没有具体error说明，如果有我自己都能解决了

**Comment by mentalfl0w** [comment]
> @mentalfl0w 我就是用Qt Online Installer安装的QT，我的QT版本是6.4.3，报错就是截图的那个，往上面查找只有一些警告，没有具体error说明，如果有我自己都能解决了

我这边在MacBook Pro 2018和MacBook Pro 2022、Mac mini 2022上编译测试均通过，是否有可能是Qt 6.4.3版本的问题？我自己一般使用LTS版本，也就是6.2.4和6.5.0，前者比较稳定，后者还是有点小问题，但编译main分支最新的代码均能通过。

**Comment by mentalfl0w** [comment]
我看你还有Qt 5.15.2，还有一种办法是切换到qt-5.15.2分支然后用Qt 5.15.2编译一下，这个分支我刚刚测试是没有问题的，如果你那边也没问题，那应该就是Qt 6.4.3的问题了。

**Comment by racall** [comment]
@mentalfl0w   在中文文档中说main分支就是使用的QT6.4.3，所以我就装了6.4.3，我有时间在试试看。请教你一个问，如何在新的工程中使用这个UI？  我昨晚试了，按照文档上说的，但是调用成功了，window窗口不显示

**Comment by mentalfl0w** [comment]
> @mentalfl0w 在中文文档中说main分支就是使用的QT6.4.3，所以我就装了6.4.3，我有时间在试试看。请教你一个问，如何在新的工程中使用这个UI？ 我昨晚试了，按照文档上说的，但是调用成功了，window窗口不显示

README文档有段时间没更新了，现在main分支用的是Qt 6.5.0，我自己用的是Qt 6.2.4和Qt 5.15.2，其他的版本我没测试过也不知道是否存在问题。
调用成功的话，如果使用的是FluWindow，需要手动将visible设置为true，或者直接用CustomWindow。

**Comment by racall** [comment]
@mentalfl0w 好的 谢谢

**Comment by shining77** [comment]
> arm64;x86_64

我的问题正好和你相反！我是9代15装的黑苹果10.15.7。提示`building for macOS-arm64 but attemping to link with file built for macOS-x86_64`，然后我替换成x86_64就能通过了！非常感谢！
