### ISSUE TITLE
Qt Creator编译出错

### ISSUE THREAD

**Issue by Diligent-SXD** [zhuzichu520/FluentUI#222]
您好，我使用Qt Creator或VS2022编译时，出现如下错误：
-- Configuring done
CMake Error at CMakeLists.txt:125 (target_link_libraries):
  Target "example" links to:

    FramelessHelper::Core

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
CMake process exited with exit code 1.
项目中framelesshelper文件夹是有文件存在的，请问我应该如何解决该问题，十分感谢您的回答，谢谢！

**Comment by racall** [comment]
@Diligent-SXD   文件夹存在里面有文件吗？按照文档中说的 使用git clone --recursive试试看

**Comment by Diligent-SXD** [comment]
> @Diligent-SXD 文件夹存在里面有文件吗？按照文档中说的 使用git clone --recursive试试看

感谢回复，项目应该直接打开根目录下的CMakeLists.txt，而不是example里面的CMakeLists.txt

**Comment by feelingsa** [comment]
为啥我是在根目录下打开的，但是也遇到了相同的问题啊，请问这个怎么解决啊.

**Comment by Diligent-SXD** [comment]
是使用QT Creator直接打开FluentUI目录下的CMakeLists.txt吗？你要确保FramelessHelper文件夹里面有文件，不是采用zip下载FluentUI

**Comment by feelingsa** [comment]
![image](https://github.com/zhuzichu520/FluentUI/assets/59379249/c78a1535-770c-444f-a3f4-9f1ccd068418)
是的呀 我直接打开FluentUI目录下的CMakeLists.txt 第一次cmake报错没有CmakeList.txt我就新建了一个空的，然后再次cmake就出现了和你一样的错误
