### ISSUE TITLE
窗口拖动背景色不会自动跟随窗口

### ISSUE THREAD

**Issue by Obsidian200** [zhuzichu520/FluentUI#226]
https://github.com/zhuzichu520/FluentUI/assets/31143076/c615797d-9916-4066-9980-fefd43b73753

录了一个视频教程

**Comment by FeJQ** [comment]
[[](https://github.com/zhuzichu520/FluentUI/issues/206)](https://github.com/zhuzichu520/FluentUI/issues/206)
