### ISSUE TITLE
当页面跳转问题

### ISSUE THREAD

**Issue by MrSSai** [zhuzichu520/FluentUI#229]
初学`Qt`，想请教`up`主。如何进行页面的跳转。

在`TaskListPage`页面中有一个`FluTableView`，在`FluTableView`的每一行后面有个`FluFilledButton`，按钮的`onClicked`触发事件需要携带该行的`dataIndex:"id"`，然后跳转到编辑页面，我想把编辑页面显示在原来的`TaskListPage`的位置（不做弹框的模式）。请问该使用那个组件呢？

**Comment by zhuzichu520** [comment]
有很多方式实现，就直接在你的TableView后面加一个Loader组件，大小位置和Tableview一样，点击跳转的时候设置sourcecomponent，返回的把sourcecomponent设置为undefined

**Comment by MrSSai** [comment]
谢谢，已实现
