### ISSUE TITLE
在使用HotLoader时，Qt保存QML文件后会关闭掉HotLoader窗口

### ISSUE THREAD

**Issue by StaticReflection** [zhuzichu520/FluentUI#234]
example版本: 1.5.0_win64_msvc2019_64_Qt6.5.0.zip
qt版本: 6.4.3

如何复现: 将qml文件拖入hotloader弹出的窗口能正常显示，当我在qt中保存文件后hotloader弹出的窗口会关闭

**Comment by StaticReflection** [comment]
Uploading QQ202389-2382.mp4…

**Comment by StaticReflection** [comment]
https://github.com/zhuzichu520/FluentUI/assets/131577661/b96193f4-0f42-457c-9350-8d0865ccc658

**Comment by StaticReflection** [comment]
> QQ202389-2382.mp4

第一次拖qml文件的时候没能成功打开

**Comment by zhuzichu520** [comment]
将FluWindow的visible属性设置成True

**Comment by StaticReflection** [comment]
> 将FluWindow的visible属性设置成True

感谢, 已解决
