### ISSUE TITLE
想问一下global里ItemsFooter.qml "/about"

### ISSUE THREAD

**Issue by Cijade** [zhuzichu520/FluentUI#237]
/about这个打开关于窗口，/about怎么定位到qml文件的

**Comment by zhuzichu520** [comment]
先在App.qml将/about添加到路由表中
https://github.com/zhuzichu520/FluentUI/blob/7fe71c892b1fcbea2393360a8ec8a8bcfc34d2ea/example/qml/App.qml#L31
然后调用FluApp中的navigate方法，传入/about参数，通过遍历路由表找到qml文件
https://github.com/zhuzichu520/FluentUI/blob/7fe71c892b1fcbea2393360a8ec8a8bcfc34d2ea/src/FluApp.cpp#L40

**Comment by Cijade** [comment]
多谢作者，我实现出来了，原来还有个App.qml
