### ISSUE TITLE
 编译不通过

### ISSUE THREAD

**Issue by chinayzt** [zhuzichu520/FluentUI#239]
[直接下载代码，可以正常运行。后压缩代码，换了目录，就不能build了。提示错误，C:\Users\yuanz\Desktop\FluentUI0815\FluentUI\.cmake\GetGitRevisionDescription.cmake:306: error: MATH cannot parse the expression: " * 10000 + * 100 + ": syntax error, unexpected exp_TIMES (2). CMakeLists.txt:7 (include)。两个问题1.原因是？2.怎么理解CMake，或者看什么书能了解编译过程。

**Comment by zhuzichu520** [comment]
看描述你应该是把.git文件删掉了。GetGitRevisionDescription.cmake作用主要是读取git提交的信息，现在删掉读不到数据就报错了。可以重新执行git init、git add ./ 、git commit -m 'update' 。主要就是用GetGitRevisionDescription.cmake获取git的tag版本号，这样每次自动化打包就不需要设置版本号了，直接从tag中获取，美滋滋的

**Comment by chinayzt** [comment]
（在新项目中使用FluentUI 这是视频）之前版本没问题 ，可以编译使用，但是最新版本就是不行，折腾两天，全部清除，重新编译，报这个错误
![image](https://github.com/zhuzichu520/FluentUI/assets/142288782/83bc3c61-ff34-4728-8f5b-c61c7d6f077e)
C:\Users\yuanz\Documents\untitled12\FluentUI\src\CMakeLists.txt:70: error: configure_file Problem configuring file
如果不用你的方法，如果直接用dll，在cmake下，怎么使用？

**Comment by zhuzichu520** [comment]
明白了，是有问题，我再修改一下。

**Comment by zhuzichu520** [comment]
https://github.com/zhuzichu520/FluentUI/commit/26669f76e0db4d1c5ef59aaadad640ced333316b

**Comment by chinayzt** [comment]
可以了 仓主！仓主威武！！！，再问一下，用什么软件加速github,Steam++吗？好像只能加速网页，不能加速命令行。

**Comment by zhuzichu520** [comment]
直接翻墙吧。。。
