### ISSUE TITLE
示例程序窗口移动到固定位置背景全透明了

### ISSUE THREAD

**Issue by llushikang** [zhuzichu520/FluentUI#243]
![image](https://github.com/zhuzichu520/FluentUI/assets/43806578/ff6f7688-35db-4b20-bef5-12e7da498073)
![image](https://github.com/zhuzichu520/FluentUI/assets/43806578/a22ebc8e-df15-4aa4-846f-074611f944b5)
不选中就是正常的
![image](https://github.com/zhuzichu520/FluentUI/assets/43806578/aa1ca25c-c394-49a4-8e23-14df05c99407)

**Comment by llushikang** [comment]
应该是win11云母材质没设置好，framelesshelper示例程序不会这样

**Comment by zhuzichu520** [comment]
#206 按这个方法关掉EnableBlurBehindWindow

**Comment by llushikang** [comment]
可以
