### ISSUE TITLE
不应假设 `CMAKE_PREFIX_PATH` 为 QT 目录

### ISSUE THREAD

**Issue by ArcticLampyrid** [zhuzichu520/FluentUI#244]
https://github.com/zhuzichu520/FluentUI/blob/26669f76e0db4d1c5ef59aaadad640ced333316b/CMakeLists.txt#L17

不应假设 `CMAKE_PREFIX_PATH` 为 QT 目录，应在 `find_package` 后使用 `Qt6_DIR`

**Comment by zhuzichu520** [comment]
已修改
https://github.com/zhuzichu520/FluentUI/blob/9bf6ed9d1d3373d3bc38fac46b97ea60644113e9/CMakeLists.txt#L23
