### ISSUE TITLE
内存与GPU占用问题

### ISSUE THREAD

**Issue by Zheng1208** [zhuzichu520/FluentUI#25]
1、随着在左侧导航栏中点开的页面增多，使用的内存越来越大，从最开始的90MB增长到了500多MB。
 2、软件开启全屏后，i5-7400 核显电脑的核显使用量能达到29%。

**Comment by zhuzichu520** [comment]
嗯，是有这种情况，原来想弄成Loader去加载页面，但是没法保存上一页面的数据。所以改成了StackView去加载页面。
