### ISSUE TITLE
FluAppBar，建议添加一个自定义的程序的logo图标功能

### ISSUE THREAD

**Issue by lihaopeng1024** [zhuzichu520/FluentUI#252]
FluAppBar，建议添加一个自定义的程序的logo图标功能，传递一个图片文件地址，显示程序logo图标。

**Comment by zhuzichu520** [comment]
main分支已添加
https://github.com/zhuzichu520/FluentUI/commit/bad1071bb4b2101685dfd91eca80160aa18696e2
