### ISSUE TITLE
FluMenu菜单控件如何添加自定义图标

### ISSUE THREAD

**Issue by lihaopeng1024** [zhuzichu520/FluentUI#256]
FluMenu菜单控件如何添加自定义图标？

**Comment by suterberg** [comment]
试了下，貌似要重写  FluMenuItem的 contentItem:

**Comment by zhuzichu520** [comment]
已添加
![1692714371609](https://github.com/zhuzichu520/FluentUI/assets/56627161/876d6548-4613-465d-9d6b-10bdf873d993)
