### ISSUE TITLE
qt creator 无法正常打开项目，我是用的qt6.2.4

### ISSUE THREAD

**Issue by weichen-1988** [zhuzichu520/FluentUI#258]
按照以下步骤操作后无法正常导入项目到qtcreator
![image](https://github.com/zhuzichu520/FluentUI/assets/60188695/8423814b-a7dd-4cd7-9b55-28a1070b8153)
![image](https://github.com/zhuzichu520/FluentUI/assets/60188695/1fce9617-e409-446f-a194-ee995ebe9f37)
![image](https://github.com/zhuzichu520/FluentUI/assets/60188695/e9c57307-6274-4049-b38c-380ffdb78361)
![image](https://github.com/zhuzichu520/FluentUI/assets/60188695/0df3a98d-0151-47bf-831f-861e7784796e)
![image](https://github.com/zhuzichu520/FluentUI/assets/60188695/482d5771-9926-4a0b-83ab-c8de5fdb04af)

**Comment by zhuzichu520** [comment]
main分支已修改，请重新下载main分支代码

**Comment by weichen-1988** [comment]
![image](https://github.com/zhuzichu520/FluentUI/assets/60188695/db9a0d07-9a9c-49f2-98b2-a03071ddb3fd)
还是会报错，现在使用6.2.4版本
