### ISSUE TITLE
无法通过编程方式正确设置 FluTimePicker 的默认值

### ISSUE THREAD

**Issue by ArcticLampyrid** [zhuzichu520/FluentUI#260]
正在考虑使用该 UI 库完成一个后台管理系统，需要类似“编辑日期”这样的功能。
假定后台信息已被设置为 “2023年1月20日”，希望能够在弹出前默认设置为 “2023年1月20日” （而非 `now`）
当前 `current` 属性仅用于返回选择的日期，设置该属性后无法直接反应到 UI 界面上

**Comment by zhuzichu520** [comment]
main分支已修改，FluTimePicker、FluDatePicker、FluCalendarPicker新增accepted信号，初始值可以通过current设置，选择触发信号onAccepted
https://github.com/zhuzichu520/FluentUI/commit/ba565e1ee8f445f9cb3024e44aafd55dbbbca712

**Comment by ArcticLampyrid** [comment]
已经可以在初始化时设置，但似乎后续对 current 的修改均无法反馈到 UI 上
