### ISSUE TITLE
很多控件只有鼠标hovered而没有鼠标pressed的视觉反应

### ISSUE THREAD

**Issue by LiuPeiqiCN** [zhuzichu520/FluentUI#27]
我看了下example程序，
FluSlider，FluToggleSwitch，FluTextBox具备hovered和pressed的视觉特效
FluButton，FluIconButton，FluNavigation缺少pressed的视觉特效
FluCheckBox缺少hovered和pressed的视觉特效

我觉得FluButton很常用，比较重要，它缺少鼠标按压的视觉效果

**Comment by zhuzichu520** [comment]
额，严格，加上......

**Comment by zhuzichu520** [comment]
1.2.1版本已经加上
