### ISSUE TITLE
module "org.wangwenx190.FramelessHelper" is not installed

### ISSUE THREAD

**Issue by CharNewbie01w** [zhuzichu520/FluentUI#277]
QQmlApplicationEngine failed to load component
qrc:/Mini_Launcher_with_Qt/main.qml:3:1: module "org.wangwenx190.FramelessHelper" is not installed
我尝试过开启或关闭FLUENTUI_BUILD_FRAMELESSHEPLER，但都不起效，请问该怎么办?

**Comment by zhuzichu520** [comment]
修改FLUENTUI_BUILD_FRAMELESSHEPLER需要Clear Camke Configuration，重新cmake一下才生效

**Comment by CharNewbie01w** [comment]
Clear Camke Configuration完然后也重新CMake了，但还是module "org.wangwenx190.FramelessHelper" is not installed

**Comment by CharNewbie01w** [comment]
我重新建了个项目，这次先导入framelesshelper，问题解决了
