### ISSUE TITLE
Qt5.14.2编译失败

### ISSUE THREAD

**Issue by cooleeryan** [zhuzichu520/FluentUI#288]
@zichu，你好，我这边用的是Qt5.14.2,MSVC 2017环境。CMake 配置成功了，但编译失败，一直很多这样的错误，请问是哪里的问题呢
```
C2059， 语法错误"}"  ,  Def.h 
C2059， 语法错误"}"  ,  Def.h 
C2059， 语法错误"}"  ,  Def.h 
C2059， 语法错误"}"  ,  Def.h 
C2059， 语法错误"}"  ,  Def.h 
```

**Comment by zhuzichu520** [comment]
main分支至少qt5.15.2

**Comment by cooleeryan** [comment]
感谢回答，main分支用6.5.2编译通过了，还有两个小问题哈
1、如果要使用Qt5.14.2，是用qt5-deprecated分支么
2、这个qt5的分支是彻底不维护了吗

**Comment by zhuzichu520** [comment]
1、qt5-deprecated兼容到qt5.12-qt5.15.2
2、qt5-deprecated已彻底不维护，main分支只保留对qt5.15.2的兼容，就是为了适配win7.....

**Comment by cooleeryan** [comment]
谢谢，准备学习Qt6了 👍
