### ISSUE TITLE
FluPivot的这个标题按钮，鼠标放上去会有系统的焦点框出现，能去掉吗

### ISSUE THREAD

**Issue by CharNewbie01w** [zhuzichu520/FluentUI#294]
![屏幕截图 2023-09-24 010942](https://github.com/zhuzichu520/FluentUI/assets/137365139/b0391355-95b6-49cf-a72b-fad8a3c769b5)
然后深色模式下是个黑框，更不好看，example里的好像就没有这种效果，但是那里边好像没写什么其他属性

**Comment by zhuzichu520** [comment]
在main函数上加上这个https://github.com/zhuzichu520/FluentUI/blob/main/example/src/main.cpp#L37

**Comment by CharNewbie01w** [comment]
哇，真的可以了，谢谢大佬
