### ISSUE TITLE
请教构建方法

### ISSUE THREAD

**Issue by masterchen** [zhuzichu520/FluentUI#295]
小白第一次接触这个用Creator导入项目， 构建设置里边和作者截图不太一样，哪位好心人能详细写一下如何配置以及出坑办法。

在问题输出界面看到：
error: include could not find requested file: cmake/utils.cmake
 error: Unknown CMake command "setup_project".
 error: CMake process exited with exit code 1.
error: CMake project configuration failed. No CMake configuration for build type "Debug" found.

在构建设置界面看到：
CMake project configuration failed. No CMake configuration for build type "Debug" found.

截图如下：

![1695621773013](https://github.com/zhuzichu520/FluentUI/assets/1975340/b5c2d389-e744-48dc-88c7-a53197b3ad7d)
![image](https://github.com/zhuzichu520/FluentUI/assets/1975340/d3608070-8302-44ea-bbda-01fd1c6899c7)

版本：
Qt Creator 11.0.1
Based on Qt 6.4.3 (MSVC 2019, x86_64)

Built on Aug 2 2023 08:49:00

**Comment by zhuzichu520** [comment]
这是代码的子模块没有clone下来，clone的时候加个参数 --recursive。git clone --recursive https://github.com/zhuzichu520/FluentUI.git

**Comment by masterchen** [comment]
太棒了， 可以了, 谢谢大神 @zhuzichu520
