### ISSUE TITLE
qt6.2.4 和6.5.2 构建都报错 ，第三个图无使用

### ISSUE THREAD

**Issue by weichen-1988** [zhuzichu520/FluentUI#296]
![image](https://github.com/zhuzichu520/FluentUI/assets/60188695/83aa6ed2-9ad3-4beb-9037-ff6526b38d89)

![image](https://github.com/zhuzichu520/FluentUI/assets/60188695/0edd2ed0-b6a2-4feb-950e-0a9e214539c6)

![image](https://github.com/zhuzichu520/FluentUI/assets/60188695/254746a4-cfff-42f1-9b3d-dd4ce372542f)

**Comment by zhuzichu520** [comment]
看着像是没有选中编译类型，选中后往下拉，点击configuration确定

**Comment by weichen-1988** [comment]
![image](https://github.com/zhuzichu520/FluentUI/assets/60188695/c1a7e9e9-2447-462f-82a2-5e91735c00c5)

就是点的底部configure project,找不到，主要是提示这个 setup_project 找不到

![image](https://github.com/zhuzichu520/FluentUI/assets/60188695/11498a1d-ae46-4735-a2ed-ff1940deadeb)

**Comment by zhuzichu520** [comment]
看下你的framlesshelper里面文件夹是不是空的，估计直接下载的代码没有子模块，用git clone代码，clone的时候加个参数 --recursive。git clone --recursive https://github.com/zhuzichu520/FluentUI.git

**Comment by weichen-1988** [comment]
![image](https://github.com/zhuzichu520/FluentUI/assets/60188695/cc9599c4-1477-4caa-aa23-b556d765ad8e)
里面不是空的，之前报了找不到的我动下载好放到对应位置了

**Comment by weichen-1988** [comment]
我尝试下克隆吧， 我本地克隆git的总是超时，建议同时在国内的某个服务商上也做个仓库

**Comment by masterchen** [comment]
你这个问题 跟我之前的一样， 大神说了 递归克隆git clone --recursive https://github.com/zhuzichu520/FluentUI.git

**Comment by weichen-1988** [comment]
已经顺利解决不知道为什么下载zip文件后解压不行
