### ISSUE TITLE
FluProgressBar的indeterminate为true时, GPU占用过高

### ISSUE THREAD

**Issue by FeJQ** [zhuzichu520/FluentUI#297]
设备为12700, RTX3070, indeterminate为false时, 几乎不占用cpu和gpu资源, 当设置为true时, 会占用20%左右的gpu资源, 请问这一块还有优化空间吗?

**Comment by zhuzichu520** [comment]
应该可以。我看代码是用QML的Canvas实现，看换成C++的如何~

**Comment by zhuzichu520** [comment]
应该没啥优化空间，我试了一下用QML自带的ProgressBar也占这么多。
