### ISSUE TITLE
FluProgressBar动态切换indeterminate属性时的bug

### ISSUE THREAD

**Issue by FeJQ** [zhuzichu520/FluentUI#298]
我的场景里会根据state动态切换indeterminate属性, 部分代码如下:
```qml
FluProgressBar {
            id: prgDownloadProgress
            indeterminate: {
                if (model.downloadState === "Connecting")
                    return true
                else if (model.downloadState === "Downloading") {
                    return !(model.totalSize || model.progress)
                }
                return false
            }
            value: model.progress
            anchors {
                bottom: parent.bottom
                left: parent.left
                right: parent.right
                bottomMargin: 10
                rightMargin: 10
            }
  }
  ```
  indeterminate一开始为true, 切换到Downloading后变为false, 此时改变进度值value, 会有概率出现界面进度不增加(永远为0), 和进度条从中间开始增加两种情况
  
  
![image](https://github.com/zhuzichu520/FluentUI/assets/41857119/53f11e02-dda0-4de5-ad44-69b83922bb49)

**Comment by zhuzichu520** [comment]
你用的是哪个版本，indeterminate为true的时候蓝条怎么这么短，我看代码里面是50%的长度。。

**Comment by zhuzichu520** [comment]
已解决，indeterminate改变false的时候，x位置没有归零。https://github.com/zhuzichu520/FluentUI/blob/36da8cd785ca35844b1ca2e95a4f714d2f0d61ae/src/Qt6/imports/FluentUI/Controls/FluProgressBar.qml#L16

**Comment by FeJQ** [comment]
感谢您
