### ISSUE TITLE
关于弹出窗口用visible的问题

### ISSUE THREAD

**Issue by imaben** [zhuzichu520/FluentUI#299]
作者您好：
我看example中有很多弹出窗口使用的是visible:true的方式，但这样会有一个问题，就是当窗口关闭再打开的时候，原来输到窗口的内容还依然存在，有没有一种通用的方法可以重绘窗口？谢谢

**Comment by zhuzichu520** [comment]
FluWindow中有个closeDestory属性，默认是true，关闭的时候会将窗口销毁掉，应该不会存在内容还存在。如果想关闭时隐藏窗口的话，可以将closeDestory属性改成false

**Comment by imaben** [comment]
closeDestroy改成true的话，关闭的时候整个窗口就真销毁了。这时再想打开 ，就只能通过createObject重新创建组件了吧。这时父窗口和子窗口建立的connection还生效吗？

**Comment by zhuzichu520** [comment]
如果是打开状态重新建立conection是生效的，如果关闭销毁那就不生效了，如果要在关闭窗口下也生效就closeDestroy改成false。。

**Comment by imaben** [comment]
所以又回到了最初的问题，怎么在这种情况下，清空原来已经输入或操作的内容。
现在是在目标窗口中写了一个方法，方法中做了 清空数据  和 visible = true
但总感觉这种做法有点low。。

**Comment by zhuzichu520** [comment]
example中有个FluViewModel组件应该可以实现，它有个scope属性，设置成FluViewModelType.Application，然后把你要保存的数据放进ViewModel中，可以看下例子https://github.com/zhuzichu520/FluentUI/blob/0e4d81c7c8e619ff531ea3399df566bab7144339/example/qml/viewmodel/TextBoxViewModel.qml#L4
