### ISSUE TITLE
作者你好，问下table组件能实现图片中的样式吗

### ISSUE THREAD

**Issue by Mizeki** [zhuzichu520/FluentUI#302]
![image](https://github.com/zhuzichu520/FluentUI/assets/26157932/dd8a02f2-dcbb-4682-ab19-7a8d66ba3ac6)

这个是qwidget实现的table，请问下qml可以实现这种样式吗，多谢

**Comment by zhuzichu520** [comment]
可以

**Comment by Mizeki** [comment]
> 可以

这个可以加入到开发计划中不  项目中用到表格的地方还挺多的 感谢感谢😁
