### ISSUE TITLE
编译失败，编译静态库，提示如下。。

### ISSUE THREAD

**Issue by ohlig** [zhuzichu520/FluentUI#303]
![image](https://github.com/zhuzichu520/FluentUI/assets/67046748/ed46e25f-d8c8-47fe-ba68-3aa0ea94108e)
![Snipaste_2023-10-08_00-11-16](https://github.com/zhuzichu520/FluentUI/assets/67046748/5dda7882-9c23-442e-b8a5-c5548e6b9581)

**Comment by zhuzichu520** [comment]
估计和动态插件冲突了，<QT_SDK_DIR_PATH>\qml\FluentUI 把这个目录下的文件夹删了
