### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by 123aaayby** [zhuzichu520/FluentUI#305]
Linking CXX shared library D:/2/FluentUI/qml/FluentUI/fluentuiplugin.dll
ld.exe: CMakeFiles/fluentuiplugin.dir/objects.a(fluentuiplugin_qmlcache_loader.cpp.obj):fluentuiplugin_qmlcache_loader.cpp:(.rdata+0x2140): undefined reference to `QmlCacheGeneratedCode::_qt_qml_FluentUI_Controls_FluWindow_qml::qmlData'

ld.exe: CMakeFiles/fluentuiplugin.dir/objects.a(fluentuiplugin_qmlcache_loader.cpp.obj):fluentuiplugin_qmlcache_loader.cpp:(.rdata+0x2ca8): undefined reference to `QmlCacheGeneratedCode::_qt_qml_FluentUI_Controls_ColorPicker_ColorPicker_qml::aotBuiltFunctions'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/fluentuiplugin.dir/build.make:3173:

**Comment by zhuzichu520** [comment]
Qt版本多少？最低支持Qt5.15.2

**Comment by 123aaayby** [comment]
6.5.2
