### ISSUE TITLE
建议：MSVC动态库输出适配Qt风格

### ISSUE THREAD

**Issue by tghul** [zhuzichu520/FluentUI#307]
msvc 
![image](https://github.com/zhuzichu520/FluentUI/assets/80230035/817c9c96-0a20-46f6-983e-ed54270971d6)

**Comment by zhuzichu520** [comment]
已添加
https://github.com/zhuzichu520/FluentUI/blob/16da5f1633eed52038aa09dc897fe7fdffded4d9/src/CMakeLists.txt#L132
