### ISSUE TITLE
Qt6.6 提供错误

### ISSUE THREAD

**Issue by o2co2** [zhuzichu520/FluentUI#308]
E:\Code2023\QT\Qt_Fusion\FluentUI\framelesshelper\src\core\utils.cpp:579: error: C2039: "AccentColor": 不是 "QPalette" 的成员
E:\Code2023\QT\Qt_Fusion\FluentUI\framelesshelper\src\core\utils.cpp(579): error C2039: "AccentColor": 不是 "QPalette" 的成员
E:\Qt\6.6.0\msvc2019_64\include\QtGui/qpalette.h(18): note: 参见“QPalette”的声明

改为
return QGuiApplication::palette().color(QPalette::Accent);

**Comment by zhuzichu520** [comment]
已同步framelesshelper最新代码
