### ISSUE TITLE
程序无法动态切换语言

### ISSUE THREAD

**Issue by LiuPeiqiCN** [zhuzichu520/FluentUI#31]
正常QML程序是可以切换语言并即时生效的，但是Fluent UI通过FluApp打开的页面无法即时更改显示语言，必须重新用FluApp打开界面才可以显示新语言。

**Comment by zhuzichu520** [comment]
嗯，国际化语言切换下周准备弄一下。

**Comment by LiuPeiqiCN** [comment]
重构FluWindow后可以动态切换语言了。
