### ISSUE TITLE
TableView是否支持高亮显示一行？

### ISSUE THREAD

**Issue by zhanglyl** [zhuzichu520/FluentUI#315]
![图片](https://github.com/zhuzichu520/FluentUI/assets/3203838/350332c0-0076-4cfd-aeb6-2b5360033599)

有时候，只是显示一组数据用，高亮显示当前行。效果如上图。
根据网上的例子，使用
import QtQuick.Controls 1.4

...
            // 设置每个单元格的字体样式
            itemDelegate: Text {
                text: styleData.value
                color: styleData.selected ? "red" : styleData.textColor
                elide: styleData.elideMode
            }

            // 设置行的背景色
            rowDelegate: Rectangle {
                color: styleData.selected ? root.highlight : root.alterBackground
            }
...
是不是 import QtQuick.Controls 2.15 之后不支持这种方式，用什么方式实现这个效果呢？

**Comment by zhuzichu520** [comment]
FluTableView已更新
![1697516691144](https://github.com/zhuzichu520/FluentUI/assets/56627161/9b19d30c-60d9-448b-8ad1-5c6de011cf4a)

**Comment by zhanglyl** [comment]
已经测试OK！赞！
