### ISSUE TITLE
CMake Error at src/CMakeLists.txt:136 (target_link_libraries):

### ISSUE THREAD

**Issue by wendao8469759** [zhuzichu520/FluentUI#317]
请教 这个是我环境有问题还是？
Build FluentUI demo applications.: ON
Build static library.: OFF
Path to FluentUI plugin.: D:/Qt/6.6.0/msvc2019_64/qml/FluentUI
-- Configuring done
CMake Error at src/CMakeLists.txt:136 (target_link_libraries):
  Target "fluentuiplugin" links to:

    FramelessHelper::Core

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

**Comment by wendao8469759** [comment]
上面那个是用命令的 
我用qt creator 11 打开CMakeLists.txt 就变成这样了
![image](https://github.com/zhuzichu520/FluentUI/assets/32348566/7016327e-62e6-42bd-be7a-506a87b407ce)

**Comment by wendao8469759** [comment]
最新git下 拉下来  framelesshelper中没有内容

**Comment by zhuzichu520** [comment]
git clone --recursive https://github.com/zhuzichu520/FluentUI.git  克隆代码的时候加个参数--recursive

**Comment by wendao8469759** [comment]
大意了， 没看到git中还有另两个git仓库

**Comment by wendao8469759** [comment]
多谢多谢哈
