### ISSUE TITLE
刷新按钮点击多次会崩溃

### ISSUE THREAD

**Issue by yorcan** [zhuzichu520/FluentUI#318]
![image](https://github.com/zhuzichu520/FluentUI/assets/22020323/f5319b21-81d6-4f1c-a87c-c546ded7d54e)
你好，
左上角第二个按钮，点击多次程序自己退出了。
最新的输出日志
QObject::killTimer: Timers cannot be stopped from another thread
QIODevice::read (QNetworkReplyHttpImpl): device not open
qml: {"downloadSavePath":"","headers":{"token":"yyds","os":"pc"},"method":"get","params":{"method":"get"},"url":"https://zhu-zichu.gitee.io/lieflat.json"}

**Comment by zhuzichu520** [comment]
出现这个QObject::killTimer: Timers cannot be stopped from another thread
QIODevice::read (QNetworkReplyHttpImpl): device not open 也不至于崩溃。Qt哪个版本？

**Comment by zhuzichu520** [comment]
你打个断点看看崩溃在什么地方

**Comment by yorcan** [comment]
6.2.4 msvc2019 64bit构建的，分支origin/main
![image](https://github.com/zhuzichu520/FluentUI/assets/22020323/5b36319c-3025-4353-9586-111f48f7cac1)

![image](https://github.com/zhuzichu520/FluentUI/assets/22020323/6bfc9100-94bb-49bb-b71f-1e772acd3294)

这一切看起来都指向了void FluHttp::get(HttpRequest* request,HttpCallable* callable)中调用onFinsish的函数对象HttpCallable的地方。

**Comment by yorcan** [comment]
打印如下：
QObject::killTimer: Timers cannot be stopped from another thread
QIODevice::read (QNetworkReplyHttpImpl): device not open
qml: {"downloadSavePath":"","headers":{"token":"yyds","os":"pc"},"method":"get","params":{"method":"get"},"url":"https://zhu-zichu.gitee.io/lieflat.json"}
onecore\net\netprofiles\service\src\nsp\dll\namespaceserviceprovider.cpp(550)\nlansp_c.dll!00007FF849EAD93D: (caller: 00007FF87375ACF6) LogHr(12) tid(304c) 8007277C 此服务不存在。在指定的命名空间中找不这个服务。

**Comment by yorcan** [comment]
我尝试从github上更新到最新的仓库版本时，发现问题已经解决了。
