### ISSUE TITLE
关于FluPivot使用的一些问题

### ISSUE THREAD

**Issue by Eve-Middleton** [zhuzichu520/FluentUI#324]
你好，我正在使用example app中的一些示例代码，如下所示
`
FluPivot{
    anchors.fill: parent
    FluPivotItem:{
        text:"All"
        contentItem: FluText{
            text:"All emails go here."
        }
    }
    FluPivotItem:{
        text:"Unread"
        contentItem: FluText{
            text:"Unread emails go here."
        }
    }
    FluPivotItem:{
        text:"Flagged"
        contentItem: FluText{
            text:"Flagged emails go here."
        }
    }
    FluPivotItem:{
        text:"Urgent"
        contentItem: FluText{
            text:"Urgent emails go here."
        }
    }
}
`
我在qt中使用改组件时，一直提示
qrc:/qml/TabBar.qml:8:29: Expected token `,'
            contentItem: FluText{
                                ^)
请问我应该如何解决，期待你的回复，谢谢。

**Comment by zhuzichu520** [comment]
贴一下TabBar代码，估计是哪行代码格式错了

**Comment by Eve-Middleton** [comment]
你好，谢谢你的回复，TabBar.qml文件如下所示：
import QtQuick 2.15
import FluentUI

FluPivot{
    anchors.fill: parent
    FluPivotItem:{
        text:"All"
        contentItem: FluText{
            text:"All emails go here."
        }
    }
    FluPivotItem:{
        text:"Unread"
        contentItem: FluText{
            text:"Unread emails go here."
        }
    }
    FluPivotItem:{
        text:"Flagged"
        contentItem: FluText{
            text:"Flagged emails go here."
        }
    }
    FluPivotItem:{
        text:"Urgent"
        contentItem: FluText{
            text:"Urgent emails go here."
        }
    }
}

**Comment by zhuzichu520** [comment]
用的Qt哪个版本？

**Comment by Eve-Middleton** [comment]
Qt 6.6.0 msvc2019

**Comment by zhuzichu520** [comment]
```
FluPivotItem:{
  text:"All"
  contentItem: FluText{
  text:"All emails go here."
}
```
FluPivotItem后面不需要 “:”

**Comment by Eve-Middleton** [comment]
你好，似乎这样才是正确的：
import QtQuick 2.15
import FluentUI

FluPivot{
    anchors.fill: parent
    FluPivotItem{
        title:"All"
        contentItem: FluText{
            text:"All emails go here."
        }
    }
    FluPivotItem{
        title:"Unread"
        contentItem: FluText{
            text:"Unread emails go here."
        }
    }
    FluPivotItem{
        title:"Flagged"
        contentItem: FluText{
            text:"Flagged emails go here."
        }
    }
    FluPivotItem{
        title:"Urgent"
        contentItem: FluText{
            text:"Urgent emails go here."
        }
    }
}
主要修改点：
1.FluPivotItem没有text属性，而是title.
2.FluPivotItem后没有:(如您所说那样)

希望能修改下example app中的示例代码。最后，谢谢你的回复。

**Comment by zhuzichu520** [comment]
exmaple代码是对的。。估计不是最新的代码
