### ISSUE TITLE
建议作者尽快规划一个稳定的大版本

### ISSUE THREAD

**Issue by imaben** [zhuzichu520/FluentUI#325]
目前感觉核心组件，每个小版本改动还是挺大。跟着滚动升级很麻烦，每次都要改很多代码才能兼容最新的代码。
建议作者可以做一下版本的规划，在迭代的过程中，小版本可以做到向前兼容，大版本小改动即可兼容这样。
毕竟是正规开源项目！

还有一点，就是commit内容尽量清晰一点（狗头

**Comment by zhuzichu520** [comment]
.....嗯，好的。哈哈确实没啥规划，都是想到哪写道哪...

**Comment by imaben** [comment]
再问个问题哈：
FluApp.nativate指向的窗口，为什么设置 modality: Qt.WindowModal不生效，我想生成一个模态窗口，除了这种方式还有别的方式吗，谢谢

**Comment by imaben** [comment]
找到原因了。改成 modality: Qt.ApplicationModal 即可

**Comment by imaben** [comment]
老哥，遇到个新问题：

SubWindow.qml
```
FluWindow {
    id: window
    appBar: com_app_bar

    Component{
        id:com_app_bar
        FluAppBar {
            title: window.title
            showStayTop: false
            icon:"qrc:/DigitalHuman/res/image/favicon.ico"
        }
    }
}
```

Test.qml
```
SubWindow {
    id: dialog
    title: "title"
    width: 680
    height: 500

    modality: Qt.ApplicationModal

    Component.onCompleted: {

    }
```

运行会报错：
<img width="344" alt="image" src="https://github.com/zhuzichu520/FluentUI/assets/3390195/f8c5ad28-f8a1-4635-9407-1fe35b241f88">

<img width="418" alt="image" src="https://github.com/zhuzichu520/FluentUI/assets/3390195/205190eb-73ce-468b-9835-50d64e9b98a4">

<img width="502" alt="image" src="https://github.com/zhuzichu520/FluentUI/assets/3390195/4632a93d-e5e1-45e7-b4a8-fd32af5ac97a">

看了看没有找到原因，希望老哥帮忙给看一下，谢谢
