### ISSUE TITLE
建议增加左侧栏仅显示图标的功能

### ISSUE THREAD

**Issue by CWenYx** [zhuzichu520/FluentUI#33]
如题

**Comment by zhuzichu520** [comment]
嗯，这个本来是想加上的，连枚举字段都预留了。后面看到没有效果也还行，就不想实现了。。。哈哈哈

**Comment by CWenYx** [comment]
哈哈哈,没有也行,就是有一点点占用左侧空间,毕竟免费+开源,我们不要求太多.后面手上的活忙完,仔细研究一下自己加也是可以的.谢谢了

**Comment by zhuzichu520** [comment]
已经加上了。。。1.2.3版本
