### ISSUE TITLE
无边框窗口来回在两个屏幕上拖动移动会产生残留

### ISSUE THREAD

**Issue by kevinlq** [zhuzichu520/FluentUI#334]
该框架无边框使用了`framelesshelper`, 猜测应该是这个库的问题。实际测试中发现在两个屏幕上来回拖动Example 程序，会产生残留以及控制台输出警告错误信息：
```
setGeometry: Unable to set geometry 973x696+623+241 (frame: 989x704+615+241) on MainWindow_QMLTYPE_103/"" on "\\.\DISPLAY1". Resulting geometry: 973x727+623+210 (frame: 989x735+615+210) margins: 8, 0, 8, 8 minimum size: 520x200 MINMAXINFO(maxSize=POINT(x=0, y=0), maxpos=POINT(x=0, y=0), maxtrack=POINT(x=0, y=0), mintrack=POINT(x=536, y=208)))
```

现象如下：
![image](https://github.com/zhuzichu520/FluentUI/assets/12824316/488827af-9341-4804-939f-cb69339dc78a)

其次，使用我自己写的 Demo 现象更明显一些：
![image](https://github.com/zhuzichu520/FluentUI/assets/12824316/495bdc74-50b8-4371-a55c-86e5ef7565a3)

**Comment by zhuzichu520** [comment]
https://github.com/wangwenx190/framelesshelper 可以给这位大佬提个issue。。哈哈，我也在写聊天Demo，准备服务端、PC端、Flutter移动端、H5管理平台全部写一遍，要不组个队0.0。。。
![1699374637484](https://github.com/zhuzichu520/FluentUI/assets/56627161/a8c54746-66e7-4d01-81bf-dd10625c9c27)

**Comment by zengdapang** [comment]
[参考这里](https://github.com/wangwenx190/framelesshelper/issues/320)

**Comment by kevinlq** [comment]
> https://github.com/wangwenx190/framelesshelper 可以给这位大佬提个issue。。哈哈，我也在写聊天Demo，准备服务端、PC端、Flutter移动端、H5管理平台全部写一遍，要不组个队0.0。。。 ![1699374637484](https://user-images.githubusercontent.com/56627161/281113454-a8c54746-66e7-4d01-81bf-dd10625c9c27.png)

嗯嗯，看了原仓库中的 `issue`，属于 `Qt` `bug` 了，那就暂时用其它版本了，不纠结了。

我看到了只是顺手写个 `demo`练练手，平时太忙了，应该没时间组队，996太忙了...

**Comment by kevinlq** [comment]
> [参考这里](https://github.com/wangwenx190/framelesshelper/issues/320)

嗯嗯，看到了，谢谢。
