### ISSUE TITLE
"favicon.ico" Not Found

### ISSUE THREAD

**Issue by Mr-Second** [zhuzichu520/FluentUI#335]
这是我目录的结构：
![Snipaste_2023-11-08_15-19-28](https://github.com/zhuzichu520/FluentUI/assets/38907693/314d3757-31f5-4498-beba-5c6df35c4321)
我按照B站视频的方式将FluentUI文件夹放到项目的目录下，然后调整了CMakeFileLists.txt文件：
```cmake
cmake_minimum_required(VERSION 3.16)

project(QMeeting VERSION 0.1 LANGUAGES CXX)

set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)
set(CMAKE_AUTOUIC ON)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_subdirectory(FluentUI)
set(FLUENTUI_BUILD_EXAMPLES OFF)
set(FLUENTUI_BUILD_STATIC_LIB OFF)
find_package(Qt6 6.4 REQUIRED COMPONENTS Quick)

qt_standard_project_setup()

qt_add_executable(appQMeeting
    main.cpp
)

qt_add_qml_module(appQMeeting
    URI QMeeting
    VERSION 1.0
    QML_FILES Main.qml
    QML_FILES qml/Avatar.qml
    QML_FILES qml/Flicker.qml
    RESOURCES ico.rc
    RESOURCES images/main_bg.jpg images/meeting.ico images/meeting.png
)

# Qt for iOS sets MACOSX_BUNDLE_GUI_IDENTIFIER automatically since Qt 6.1.
# If you are developing for iOS or macOS you should consider setting an
# explicit, fixed bundle identifier manually though.
set_target_properties(appQMeeting PROPERTIES
#    MACOSX_BUNDLE_GUI_IDENTIFIER com.example.appQMeeting
    MACOSX_BUNDLE_BUNDLE_VERSION ${PROJECT_VERSION}
    MACOSX_BUNDLE_SHORT_VERSION_STRING ${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}
    MACOSX_BUNDLE TRUE
    WIN32_EXECUTABLE TRUE
)

target_link_libraries(appQMeeting
    PRIVATE Qt6::Quick
    fluentuiplugin
)

include(GNUInstallDirs)
install(TARGETS appQMeeting
    BUNDLE DESTINATION .
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
)

```
编译套件信息：
> Qt 6.6.0 MSVC 2019 64bit
报错信息截图：
![Snipaste_2023-11-08_15-14-19](https://github.com/zhuzichu520/FluentUI/assets/38907693/ce56c6ff-8a3a-4388-b4ae-2c43a90b54cb)

**报错的目录确实不存在，按理来说目录应该是：**
**F:/Code_WorkSpace/QtWorkSpace/QMeeting/FluentUI/example/favicon.ico**
但是不知道为什么少了FluentUI这一级目录？

**Comment by zhuzichu520** [comment]
重新Cmake一下，你设置了set(FLUENTUI_BUILD_EXAMPLES OFF)，怎么会还需要F:/Code_WorkSpace/QtWorkSpace/QMeeting/FluentUI/example/favicon.ico这个文件呢，估计是set(FLUENTUI_BUILD_EXAMPLES OFF)无效，需要重新重新CMake

**Comment by Mr-Second** [comment]
> 重新Cmake一下，你设置了set(FLUENTUI_BUILD_EXAMPLES OFF)，怎么会还需要F:/Code_WorkSpace/QtWorkSpace/QMeeting/FluentUI/example/favicon.ico这个文件呢，估计是set(FLUENTUI_BUILD_EXAMPLES OFF)无效，需要重新重新CMake

我把QT_SDK下的qml/FluentUI目录、build目录以及项目下的out目录都删除了，然后重新构建，现在是报另外一个错误：
![Snipaste_2023-11-08_17-00-28](https://github.com/zhuzichu520/FluentUI/assets/38907693/b1d196e4-9dee-4aa6-aef7-db36d206b0a0)

**Comment by zhuzichu520** [comment]
已修改，再试试
https://github.com/zhuzichu520/FluentUI/commit/dfb80e70eefe81091f76d2b4e137e41c3af8d782

**Comment by Mr-Second** [comment]
编译通过了，感谢🤞
