### ISSUE TITLE
FluNavigationView无法只初始化一次页面

### ISSUE THREAD

**Issue by FeJQ** [zhuzichu520/FluentUI#337]
当pageMode为Auto或Minimal时,  页面的onCompleted未触发;   为Compact, open , no stack, stack时, 每次切换导航, 页面的onCompleted都会重新被调用.    是否存在一种方式,  使得每个页面被打开时才加载, 且无论如何都只加载一次?

**Comment by zhuzichu520** [comment]
可以的，FluPage的launchMode设置成FluPageType.SingleInstance。FluNavigationView设置成stack就行了
