### ISSUE TITLE
ImageProvider 传不到 FluApp 打开的界面里面去

### ISSUE THREAD

**Issue by LiuPeiqiCN** [zhuzichu520/FluentUI#34]
```engine.addImageProvider("processedImg", new ImageProvider);```
报错：QML Image: Failed to get image from provider: image://processedimg/1

**Comment by LiuPeiqiCN** [comment]
也不止 QQuickImageProvider，FluApp::init 除了把 main.cpp 里的 properties 传给了新窗口的 rootContext，其他的都没有传过去，其中就包括 ImageProvider。

**Comment by zhuzichu520** [comment]
嗯，是有这个问题，后面会把FluWindow重构一下，不用QuickView，直接用QML的Window。

**Comment by zhuzichu520** [comment]
1.2.4版本已经解决了，改用QML的Window。可以再看看还有问题不

**Comment by LiuPeiqiCN** [comment]
> 1.2.4版本已经解决了，改用QML的Window。可以再看看还有问题不

好像重构后界面打开的动画没有了。
