### ISSUE TITLE
请问，FluentIcons.Error 这些图标是在哪定义的呢？我找不到

### ISSUE THREAD

**Issue by zhin2929** [zhuzichu520/FluentUI#346]
如题，FluentIcons 定义了很多图标，请问是怎么实现的呢？

**Comment by zhin2929** [comment]
如果想扩展图标，请问怎么做呢？

**Comment by zhin2929** [comment]
看到了，是这个Segoe_Fluent_Icons字体加载的吧。可是我还是不知道FluentIcons这个名字是怎么来的

**Comment by zhin2929** [comment]
知道了，是在Def.h文件定义的。这个字体有多少图标呀？作者要考虑用FontAwesome吗

**Comment by zhin2929** [comment]
在FluentUI中，如果我想用一般的资源做图标，比如svg,png等，可以吗？FluObject 的icon属性。

**Comment by zhuzichu520** [comment]
800多个吧，svg和png资源那直接可以用自带的Image显示....

**Comment by zhin2929** [comment]
> 800多个吧，svg和png资源那直接可以用自带的Image显示....
我意思是要改变FluentUI组件的图标，比如FluPaneItemExpander的icon，我想用自己的一个图标svg，在字体里是没有的，要怎么做呢？

**Comment by zhin2929** [comment]
> 我意思是要改变FluentUI组件的图标，比如FluPaneItemExpander的icon，我想用自己的一个图标svg，在字体里是没有的，要怎么做呢？

我意思是要改变FluentUI组件的图标，比如FluPaneItemExpander的icon，我想用自己的一个图标svg，在字体里是没有的，要怎么做呢？

**Comment by zhuzichu520** [comment]
有个iconDelegate字段，可以设置一个Image
https://github.com/zhuzichu520/FluentUI/blob/e3e4592ea4beee98afb262eb52b84c7685477821/src/Qt6/imports/FluentUI/Controls/FluPaneItemExpander.qml#L14

**Comment by zhin2929** [comment]
> 有个iconDelegate字段，可以设置一个Image
> 
> https://github.com/zhuzichu520/FluentUI/blob/e3e4592ea4beee98afb262eb52b84c7685477821/src/Qt6/imports/FluentUI/Controls/FluPaneItemExpander.qml#L14

好的，谢谢。
