### ISSUE TITLE
ListView画面撕裂

### ISSUE THREAD

**Issue by FeJQ** [zhuzichu520/FluentUI#347]
感觉可能不是FluentUI的问题, 不过还是想向您请教一下, 这种问题该如何解决?
滑动, 悬浮,  都会有明显的闪烁,  偶尔会像下图一样出现撕裂的效果
![image](https://github.com/zhuzichu520/FluentUI/assets/41857119/a9173463-cda8-4451-bacd-75a2bbca77ec)

**Comment by zhuzichu520** [comment]
额，用的是哪个版本，1.6.0有中FluApp新增了一个vsync，默认是false，可能是这个原因造成的，1.6.1默认改成true了
https://github.com/zhuzichu520/FluentUI/blob/e3e4592ea4beee98afb262eb52b84c7685477821/src/FluApp.cpp#L17

**Comment by FeJQ** [comment]
> 额，用的是哪个版本，1.6.0有中FluApp新增了一个vsync，默认是false，可能是这个原因造成的，1.6.1默认改成true了
> 
> https://github.com/zhuzichu520/FluentUI/blob/e3e4592ea4beee98afb262eb52b84c7685477821/src/FluApp.cpp#L17

还真是.  之前用的1.5.6, 升级为1.6.2后,  闪烁, 撕裂, 最大化时卡顿的问题都没了
