### ISSUE TITLE
颜色组件的文字未居中

### ISSUE THREAD

**Issue by zhin2929** [zhuzichu520/FluentUI#349]
![image](https://github.com/zhuzichu520/FluentUI/assets/15818471/0378e45f-b845-4a51-a38c-dd096b8a0ba0)
原项目的界面是居中的：
![image](https://github.com/zhuzichu520/FluentUI/assets/15818471/24fbe8e0-805e-405d-8422-8b37b605915e)

**Comment by zhin2929** [comment]
好像输入框的长度也未对齐

**Comment by zhuzichu520** [comment]
后面这个组件还会再修改一下，改成这种样式
![1700812439533](https://github.com/zhuzichu520/FluentUI/assets/56627161/e476d3a4-e921-4132-b32e-422d38d78469)

**Comment by zhuzichu520** [comment]
已修改
![1709690660847](https://github.com/zhuzichu520/FluentUI/assets/56627161/2b734320-7f04-4e0c-9377-fc09853ecd76)
