### ISSUE TITLE
setting 与 左上角菜单按钮出现的覆盖问题

### ISSUE THREAD

**Issue by Pygone** [zhuzichu520/FluentUI#35]
![image](https://user-images.githubusercontent.com/90099340/230900173-910d9b85-329c-4a04-94da-d66093f4135c.png)

**Comment by Pygone** [comment]
当我在minimal setting的前提下, 点击左上角的菜单按钮, 菜单就会覆盖setting 页面, 小意见是可以设置为点击菜单按钮自动跳转为正确的setting

**Comment by zhuzichu520** [comment]
嗯，已经ok了

**Comment by Pygone** [comment]
![image](https://user-images.githubusercontent.com/90099340/230921314-35250da5-7f6b-426e-bd4d-47f57bdbb3d9.png)

**Comment by Pygone** [comment]
仍存在覆盖问题
