### ISSUE TITLE
1.6.2版本，FluComboBox下拉框影响FluSpinBox，导致刷新异常

### ISSUE THREAD

**Issue by 123Easonchen** [zhuzichu520/FluentUI#350]
1.5.8版本无此问题，经验证，是1.6.2版本中FluSpinBox里面的控件从 FluItem改为FluRectang出现了这个问题
![1700703924154](https://github.com/zhuzichu520/FluentUI/assets/50862329/a5d6e584-4255-4e27-86d3-09cf34ae5c1b)

**Comment by zhin2929** [comment]
如何修复呢？

**Comment by zhuzichu520** [comment]
FluRectangle 写成FluClip试试。

**Comment by zhuzichu520** [comment]
https://github.com/zhuzichu520/FluentUI/commit/05251e085c6f66d64d77916bbfd78ef9f7d05ce5
