### ISSUE TITLE
frameless取消编译开关后感觉迁移新工程不便

### ISSUE THREAD

**Issue by inhowe** [zhuzichu520/FluentUI#352]
frameless取消编译开关后感觉新工程适配不方便，目前尝试了以下几种方法：
1. 分别编译FluentUI、frameless并注册到qt安装目录下，自己的新工程运行时直接import fluentio，但还需要拷贝frameless的dll文件才能运行，另外需要修改frameless的编译脚本支持mingw编译，动作比较多
2. 添加FluentUI进工程后，先修改FluentUI下CMakeLists.txt，屏蔽frameless编译，在新工程下另外添加frameless目录，不方便保持FluentUI是最新状态
3. 添加FluentUI进工程直接编译，则需要参考调用例程中的app.qml来间接启动FluWindow，否则会有frameless install报错，需要2个qml配合才能把窗口显示出来。对于一些换皮旧工程，有很多子窗口可能需要逐步替换，这样子不能自由使用FluWindow。

现在看起来B站上的适配方式是比较合适的，无需修改子仓库，也无需另外拷贝dll库。
请问作者有没有推荐的迁移方案？或者是否考虑优化一下这块

**Comment by zhuzichu520** [comment]
目前main分支采用的时第3种方式，直接将frameless静态库方式编译到FluentUI中了。可以通过FluApp.useSystemAppBar属性控制是否采用系统边框还是自定义边框https://github.com/zhuzichu520/FluentUI/blob/3b4c32752847a2fafd65d9ad2df4e87c40c9b76d/example/qml-Qt6/App.qml#L45

**Comment by zhuzichu520** [comment]
已经删除framelesshelper三方库，新增FluFramelessHelper.cpp
