### ISSUE TITLE
请问，如何在C++调用showInfo呢？

### ISSUE THREAD

**Issue by zhin2929** [zhuzichu520/FluentUI#355]
如题，需要在C++中触发提示，该怎么写呢？QMetaObject::invokeMethod 吗？QML新手，求助各位大佬！

**Comment by zhuzichu520** [comment]
C++通过Q_EMIT发信号给QML，QML通过Connections组件监听信号

**Comment by zhin2929** [comment]
> C++通过Q_EMIT发信号给QML，QML通过Connections组件监听信号

解决了，感谢作者大大，能不能加个联系方式，跟您学习一下，赞助500，大概就是问类似上面这种问题，主要是一些思路不知道怎么用QML实现，您有时间回答一下就行。

**Comment by zhuzichu520** [comment]
额，大方！！！微信：hellowzzc！！！

**Comment by zhin2929** [comment]
> 大方！！！微信：hellowzzc！！！额，我尽力而为

已加微信！
