### ISSUE TITLE
FluWindow启动时最大化问题

### ISSUE THREAD

**Issue by 18357588507** [zhuzichu520/FluentUI#356]
如何FluWindow启动时窗口最大化？

**Comment by zhin2929** [comment]
兄弟，你知道怎么在C++调用QML的 showInfo 吗？

**Comment by zhuzichu520** [comment]
FluWindow新增autoMaximize属性，如果为true默认启动是最大化
https://github.com/zhuzichu520/FluentUI/blob/55a77eba4b46c82f2647fc167d0e46a834b7ec59/src/Qt6/imports/FluentUI/Controls/FluWindow.qml#L41
