### ISSUE TITLE
cmake生成vs 2022工程文件，vs打开后报错，请问该如何解决呢？

### ISSUE THREAD

**Issue by zhin2929** [zhuzichu520/FluentUI#357]
qt creator 打开后可以编译成功，但是在命令行生成vs项目文件，vs打开后报错。不知道咋解决。

**Comment by zhin2929** [comment]
这个错误，好像复制生成的dll失败了
```
  正在生成代码...
    正在创建库 D:/code/xmake/FluentUI/build/src/Release/fluentuiplugin.lib 和对象 D:/code/xmake/FluentUI/build/src/Release/flue
  ntuiplugin.exp
  fluentuiplugin.vcxproj -> D:\code\xmake\FluentUI\build\src\Release\fluentuiplugin.dll
  Copying qmldir to binary directory    Copying qmltypes to binary directory    Copying Lib to binary plugin directory
  Install library and aditional files
  Error copying file "D:/code/xmake/FluentUI/build/src/fluentuiplugin.dll" to "D:/code/xmake/FluentUI/build/src/Release
  /FluentUI".
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5):
error MSB3073: 命令“setlocal [D:\code\xmake\FluentUI\build\src\fluentuiplugin.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5):
error MSB3073: "C:\Program Files\CMake\bin\cmake.exe" -E make_directory D:/Qt/5.15.2/msvc2019_64/qml/FluentUI [D:\code\
xmake\FluentUI\build\src\fluentuiplugin.vcxproj]
```

**Comment by zhin2929** [comment]
路径不正确，把debug和release里面的dll移动到上一层目录才可以构建成功。我这是手动移动的，不知道cmakelist在哪里修改？
![image](https://github.com/zhuzichu520/FluentUI/assets/15818471/b63c6548-f344-4b52-81f7-2bf67fd378fa)

**Comment by zhuzichu520** [comment]
可以设置FLUENTUI_QML_PLUGIN_DIRECTORY  控制FluentUI插件生成目录位置
https://github.com/zhuzichu520/FluentUI/blob/8662eb97aa90ebdddd61ad27741f74c2fca80076/CMakeLists.txt#L22

**Comment by zhin2929** [comment]
> 可以设置FLUENTUI_QML_PLUGIN_DIRECTORY 控制FluentUI插件生成目录位置
> 
> https://github.com/zhuzichu520/FluentUI/blob/8662eb97aa90ebdddd61ad27741f74c2fca80076/CMakeLists.txt#L22

已经设置了，还是没用，就是设置之后还是报这个错误。
PS D:\code\xmake\FluentUI\build> cmake .. -DCMAKE_PREFIX_PATH="D:\\Qt\\5.15.2\\msvc2019_64" -DFLUENTUI_QML_PLUGIN_DIRECTORY="D:\\code\\xmake\\FluentUI\\build\\output" -DCMAKE_RUNTIME_OUTPUT_DIRECTORY="D:\\code\\xmake\\FluentUI\\build\\src"   -DCMAKE_LIBRARY_OUTPUT_DIRECTORY="D:\\code\\xmake\\FluentUI\\build\\src"  -DCMAKE_BUILD_TYPE=Release -G"Visual Studio 17 2022"
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
-- Current .git exist
-- Current git tag: 1.6.2, commit count: 955, describe: 1.6.2
-- Current semver: major: 1, minor: 6, patch: 2, counter: 10602
FLUENTUI_QML_PLUGIN_DIRECTORY===== D:/code/xmake/FluentUI/build/output
------------------------ FluentUI ------------------------
Build FluentUI demo applications.: ON
Build static library.: OFF
Path to FluentUI plugin.: D:/code/xmake/FluentUI/build/output
-- Configuring done (0.5s)
-- Generating done (0.2s)
-- Build files have been written to: D:/code/xmake/FluentUI/build

**Comment by zhuzichu520** [comment]
试试换下文件分隔符，我看这个日志中有些路径是"\"，有写路径是"/"

**Comment by zhin2929** [comment]
> 试试换下文件分隔符，我看这个日志中有些路径是"\"，有些路径是"/"

还是不行。奇怪了。而且好像也不是根据插件目录去复制的，就是固定在src下复制的，插件目录改成啥，都是在这个目录`D:\code\xmake\FluentUI\build\src`复制
```
cmake .. -DCMAKE_PREFIX_PATH="D:/Qt/5.15.2/msvc2019_64" -DFLUENTUI_QML_PLUGIN_DIRECTORY="D:/code/xmake/FluentUI/build/src"  -DCMAKE_BUILD_TYPE=Release -G"Visual Studio 17 2022"
```

**Comment by zhin2929** [comment]
但是vs工程文件，生成的dll，分别在src/debug 和 src/release 下。。。不知道是cmake的问题？还是配置的问题？
