### ISSUE TITLE
请教下，开发的时候如何实时预览界面

### ISSUE THREAD

**Issue by cfscn** [zhuzichu520/FluentUI#360]
请教下，fluentui 怎么开发的时候实时预览界面效果啊？每次写完还要编译运行。开发效率太低了！

**Comment by kevinlq** [comment]
> 请教下，fluentui 怎么开发的时候实时预览界面效果啊？每次写完还要编译运行。开发效率太低了！

试着把你启动加载 `QML`的代码这样修改下：

```
const auto qmlRes = "file:///D:/project/FluentUI/example/qml-Qt6/app.qml"
engine.load(qmlRes);
```

为了方便，还可以把加载方式改为配置文件，正式发布版本打包的时候写成 qrc:/xxx/app.qml

平时你开发调试的时候直接指定到本地文件，更方便一些。

**Comment by suterberg** [comment]
只是qml的话可以用example里的热加载试试，如果要结合后端还是要编译。

**Comment by suterberg** [comment]
> 请教下，fluentui 怎么开发的时候实时预览界面效果啊？每次写完还要编译运行。开发效率太低了！

使用 QtDesignstudio可以实时加载界面
