### ISSUE TITLE
可以考虑将frameless做成类似于fluentui的qml组件么?

### ISSUE THREAD

**Issue by suterberg** [zhuzichu520/FluentUI#362]
能不能把frameless的组件单独摘出来,qt可以使用宏来注册类型, 就不需要在c++里边注册类型了.这样更qml一些

**Comment by zhuzichu520** [comment]
动态库是可以用宏注册的，现在是编译成静态库到FluentUI中了，所以C++那边需要FramelessHelper::Quick::registerTypes(engine);进行注册

**Comment by AvansQiang** [comment]
我在自己新建的工程中遇到了 module "org.wangwenx190.FramelessHelper" is not installed。

**Comment by AvansQiang** [comment]
FramelessHelper::Quick::registerTypes(engine);

**Comment by AvansQiang** [comment]
我在自己新建的demo 工程里， 遇到了“module "org.wangwenx190.FramelessHelper" is not installed”  。 这一句， FramelessHelper::Quick::registerTypes(engine);       需要加在哪里啊， 我不太懂这个

**Comment by suterberg** [comment]
> 我在自己新建的demo 工程里， 遇到了“module "org.wangwenx190.FramelessHelper" is not installed” 。 这一句， FramelessHelper::Quick::registerTypes(engine); 需要加在哪里啊， 我不太懂这个

app.qml 里边有个FluApp.init(app)，这个是注册类的函数和界面入口，不在cpp里边
