### ISSUE TITLE
Win10下，不使用系统的标题栏拖动程序至屏幕边缘停靠，松开鼠标程序无法全屏

### ISSUE THREAD

**Issue by ZhaZhaXie1024** [zhuzichu520/FluentUI#373]
环境：
2023/12/16 16:35:38.650[Info][Log.cpp:189][4256]:[AppName] "example"
2023/12/16 16:35:38.650[Info][Log.cpp:190][4256]:[AppVersion] 1.6.4
2023/12/16 16:35:38.651[Info][Log.cpp:199][4256]:  [Manufacturer] "Windows 10 build 19045"
2023/12/16 16:35:38.651[Info][Log.cpp:200][4256]:  [CPU_ABI] "x86_64"

Qt 6.4.3 MinGW 64，我的Qt组件如下：
![image](https://github.com/zhuzichu520/FluentUI/assets/68524691/bb9e1eb7-e0c6-49aa-9c03-c6db4b6267a3)

例如以下停靠后出现的动画（后买你有个透明的背景框），这个时候松开鼠标后程序会最大化：
![image](https://github.com/zhuzichu520/FluentUI/assets/68524691/616616d6-46b8-4b6f-ac99-a0d0b43dda30)

而实例程序不行：
![image](https://github.com/zhuzichu520/FluentUI/assets/68524691/a064a050-cea9-43c4-8f6d-a8ca8dd39886)

但奇怪的是，我下载的Release，MinGW 64版本安装上却是可行的。难道我编译的时候少做了什么操作吗？

**Comment by ZhaZhaXie1024** [comment]
我切换到了1.6.4-framelesshelper这个分支，编译好之后跑起来也是不行，┓(;´_｀)┏

**Comment by zhuzichu520** [comment]
1..6.4应该是可以的，这个分支用的是framelesshelper。mian分支已经不支持了，删掉了framelesshelper，新增FluFrameless，还不支持这个，目前还再研究怎么弄，你也可以看看FluFrameless.cpp这个，看怎么用最少量代码去实现这个边缘最大化效果。。。

**Comment by zhuzichu520** [comment]
重新再拉下main分支代码看看。。

**Comment by ZhaZhaXie1024** [comment]
哇哦，可以了，我去看看怎么实现的
