### ISSUE TITLE
macOS下的窗口没有圆角

### ISSUE THREAD

**Issue by tinybug** [zhuzichu520/FluentUI#376]
@zhuzichu520 您好，macOS下的窗口没有圆角，看着比较奇怪，如下图所示

<img width="1029" alt="image" src="https://github.com/zhuzichu520/FluentUI/assets/3439875/ed63ef43-1046-417f-90bf-dc36b09a3d70">

可否使用这里的方案实现无边框的窗口[https://github.com/Bringer-of-Light/Qt-Nice-Frameless-Window/blob/master/framelesswindow/framelesswindow.mm](url)，他这个可以做到无边框，这个使用到了一些OC代码，改动比较多，希望您可以集成一下，谢谢。

**Comment by zhuzichu520** [comment]
圆角这么丑，不需要圆角。。。

**Comment by tinybug** [comment]
行吧，我有空自己整一下 😂，只是想着可以和系统的UI一致
