### ISSUE TITLE
example_1.6.5_win32_msvc2019_Qt5.15.2.exe, 安装的程序在双屏情况下，跨越屏幕时UI会错位，点最大化后点向下还原后UI恢复正常

### ISSUE THREAD

**Issue by Zero1PP** [zhuzichu520/FluentUI#377]

**Comment by Zero1PP** [comment]
测试环境为win10系统

**Comment by zhuzichu520** [comment]
额，我这没有复现出来，能录个git或视频看看不，是完全跨越后，还是程序一半在A屏幕一半在B屏幕？

**Comment by zhuzichu520** [comment]
额，复现出来了，要慢慢拖动转移到另一个屏幕......还是偶现。。。

**Comment by Zero1PP** [comment]
复现就好，我的是必现的，只要跨屏幕就错位

**Comment by zhuzichu520** [comment]
你的主窗口也会？

**Comment by Zero1PP** [comment]
对，我的就是主窗口必现

**Comment by zhuzichu520** [comment]
截个图我瞅瞅是怎么一个错位。。

**Comment by Zero1PP** [comment]
![Uploading IMG_4304.jpg…]()

**Comment by Zero1PP** [comment]
![IMG_4304](https://github.com/zhuzichu520/FluentUI/assets/52225758/27dd122f-c829-4e6b-b77e-2d81ca047378)

**Comment by Zero1PP** [comment]
只是界面错位，按钮功能还是在原来的位置才能触发

**Comment by zhuzichu520** [comment]
额，很奇怪。。Qt6是好的。Qt5有问题，试试窗口拉伸一下是不是就好了

**Comment by Zero1PP** [comment]
对拉伸一下就好了

**Comment by Zero1PP** [comment]
如果我打开程序后，先缩放两下，然后一直左右跨屏幕时，前几下跨屏幕不错位，多是几下又错位了

**Comment by zhuzichu520** [comment]
已修改，麻烦有时间的话拉个主分支代码再试试。。
https://github.com/zhuzichu520/FluentUI/commit/a851696eb00b753503d5019abe46faf033b60683

**Comment by Zero1PP** [comment]
可以了，非常完美
