### ISSUE TITLE
可以给FluText 加个过度动画么，类似于下边

### ISSUE THREAD

**Issue by suterberg** [zhuzichu520/FluentUI#378]
import QtQuick
import QtQuick.Controls
import FluentUI

Text {
    property color textColor: FluTheme.fontPrimaryColor
    property bool animi: false
    id:text
    color: textColor
    renderType: FluTheme.nativeText ? Text.NativeRendering : Text.QtRendering
    font: FluTextStyle.Body
    Behavior on text{
        enabled:text.animi
        SequentialAnimation {
            
            NumberAnimation { target: text; property: "opacity"; to: 0.0; duration: 100 }
            PropertyAction { target: text; property: "text" }
            NumberAnimation { target: text; property: "opacity"; to: 1.0; duration: 500 }   
        }
    }
}

**Comment by zhuzichu520** [comment]
这个放外面吧，不写进FluText中了，大部分需求是不需要动画的。

**Comment by suterberg** [comment]
ok,那我自己加进去了，主要是部分输出显示为flutext时候修改需要个动画来提示一下，不然值变化有点突然
