### ISSUE TITLE
可否给FluColorSet增加QML_NAMED_ELEMENT

### ISSUE THREAD

**Issue by EveryOrigin** [zhuzichu520/FluentUI#385]
我做出了如下修改:

    class FluColorSet : public QObject
      {
          Q_OBJECT
          Q_PROPERTY_AUTO(QString,darkest)
          Q_PROPERTY_AUTO(QString,darker)
          Q_PROPERTY_AUTO(QString,dark)
          Q_PROPERTY_AUTO(QString,normal)
          Q_PROPERTY_AUTO(QString,light)
          Q_PROPERTY_AUTO(QString,lighter)
          Q_PROPERTY_AUTO(QString,lightest)
          // 增加这一行
          QML_NAMED_ELEMENT(FluColorSet)
    }

在example的App.qml内使用:

        FluColorSet {
            id: customThemeColor
            darkest: "#006E5B"
            darker: "#007C67"
            dark: "#00977D"
            normal: "#00B294"
            light: "#26BDA4"
            lighter: "#4DC9B4"
            lightest: "#60CFBC"
        }
    
        Component.onCompleted: {
            FluTheme.themeColor = customThemeColor
        }

只使用FluColors里的预定义颜色有时候不是很能满足需求, 比如需要使用自定义的产品主色调之类的..

**Comment by zhuzichu520** [comment]
嗯嗯，可以的

**Comment by zhuzichu520** [comment]
已添加
https://github.com/zhuzichu520/FluentUI/blob/0b0fbe1e642692812029406d12bed13db2401a1e/src/FluColorSet.h#L21

**Comment by EveryOrigin** [comment]
> 已添加
> 
> https://github.com/zhuzichu520/FluentUI/blob/0b0fbe1e642692812029406d12bed13db2401a1e/src/FluColorSet.h#L21

感谢
