### ISSUE TITLE
"FluTabViewType"里的枚举类型“Nerver”貌似拼写错误，enum type "Nerver" in "FluTabViewType" seems incorrect

### ISSUE THREAD

**Issue by KazeFx2** [zhuzichu520/FluentUI#388]
in `Def.h`
`enum CloseButtonVisibility {
    Nerver = 0x0000,
    Always = 0x0001,
    OnHover = 0x0002
};
Q_ENUM_NS(CloseButtonVisibility)`
大概是‘Never’而不是‘Nerver’（？
强迫症犯了，不是什么重要问题 :）
did you mean the 'Never'? instead of the 'Nerver'
not a vital issue

**Comment by zhuzichu520** [comment]
已修改
https://github.com/zhuzichu520/FluentUI/blob/cc4e88adbd4ee2eb8d7a52ffeb3b4bf8f22299b8/src/Def.h#L148
