### ISSUE TITLE
在Win7中使用不使用System AppBar会超级卡顿，无法使用

### ISSUE THREAD

**Issue by jeffrey0326** [zhuzichu520/FluentUI#398]
2024/01/08 12:29:56.323[Info][Log.cpp:193][4432]:[AppName] "example"
2024/01/08 12:29:56.323[Info][Log.cpp:194][4432]:[AppVersion] 1.6.6
2024/01/08 12:29:56.323[Info][Log.cpp:196][4432]:[ProcessId] "8044"
2024/01/08 12:29:56.323[Info][Log.cpp:200][4432]:[GitHashCode] 1.6.6-24-gd397b88
2024/01/08 12:29:56.323[Info][Log.cpp:203][4432]:  [Manufacturer] "Windows 7 build 7601"
2024/01/08 12:29:56.323[Info][Log.cpp:204][4432]:  [CPU_ABI] "x86_64"
2024/01/08 12:29:56.323[Info][Log.cpp:205][4432]:[LOG_LEVEL] 4
启动得日志信息如上，鼠标点一下都很难，在未删除framelessHelper之前，是可以正常使用的，最新版本就卡了
![截图_2024-01-08_12-29-32](https://github.com/zhuzichu520/FluentUI/assets/60976594/37dec7f2-d6a7-47ce-996d-e6ec4eefc994)

**Comment by zhuzichu520** [comment]
已修改，重新拉取main分支代码试试
https://github.com/zhuzichu520/FluentUI/commit/993de241cb91e1b4514f035d3ca1e51ad7ad90c4

**Comment by zhuzichu520** [comment]
然后把C:\Users\Administrator\AppData\Local\ZhuZiChu\FluentUI\example.ini 中的配置文件删掉。看界面好像是使用了software渲染才导致变卡的
