### ISSUE TITLE
FluTableView序号列如何隐藏

### ISSUE THREAD

**Issue by 13477001653** [zhuzichu520/FluentUI#401]
![image](https://github.com/zhuzichu520/FluentUI/assets/69187939/00649112-37e4-4c80-bd3a-2fbfb5b2e77f)
怎么去除这个序号列

**Comment by zhuzichu520** [comment]
目前还有没暴露可以隐藏的属性，后续加上。。

**Comment by zhuzichu520** [comment]
FluTableView已新增horizonalHeaderVisible与verticalHeaderVisible两个属性
