### ISSUE TITLE
FluChart放在FluContentDialog里，关闭弹窗再次打开会报错

### ISSUE THREAD

**Issue by 13477001653** [zhuzichu520/FluentUI#403]
![image](https://github.com/zhuzichu520/FluentUI/assets/69187939/10848e9f-4f12-45fb-a18d-8cf9d84e402e)

**Comment by zhuzichu520** [comment]
有示例代码么~我复现一下

**Comment by 13477001653** [comment]
> 有示例代码么~我复现一下

![image](https://github.com/zhuzichu520/FluentUI/assets/69187939/d3671720-2996-4158-b3ac-f0f330571fca)
![image](https://github.com/zhuzichu520/FluentUI/assets/69187939/5863268f-8846-4ec3-a0ed-0d33a43eacae)
![image](https://github.com/zhuzichu520/FluentUI/assets/69187939/1d4c35fe-5f8b-45b7-afca-d0d78056215a)

**Comment by zhuzichu520** [comment]
感觉像是Dialog close后导致什么资源释放。然后再次显示就出了问题。。你可以把FluChart 放到 FluContentDialog的contentDelegate属性中，具体我在exmaple的T_Dialog.qml中添加了代码示例
https://github.com/zhuzichu520/FluentUI/commit/0222a2111d5cb9d5ed15c97f4109f3738c09a257
![image](https://github.com/zhuzichu520/FluentUI/assets/56627161/590dd67b-82a9-4d0f-a1fe-8dfae1aab0d1)
