### ISSUE TITLE
FluExpander在结合ScrollView和TextArea使用时，TextArea第一次展开时无文本

### ISSUE THREAD

**Issue by weypro** [zhuzichu520/FluentUI#408]
测试代码如下（可直接替换example内示例）：
```
FluExpander {
                Layout.topMargin: 20
                headerText: "打开一个滑动文本框"
                Item {
                    anchors.fill: parent
                    ScrollView {
                        anchors.fill: parent
                        TextArea {
                            id: text_info
                            width: parent.width
                            wrapMode: Text.WrapAnywhere
                            padding: 14
                            text: "先帝..."
                        }
                    }
                }
            }
```
预期效果：给TextArea加上滚动条，并且能够在展开后就能直接看到文本
实际效果：FluExpander展开后出现TextArea，但里面没有显示文本。在选中TextArea后出现文本。
以下是选中前后截图：
![屏幕截图 2024-01-22 132622](https://github.com/zhuzichu520/FluentUI/assets/22854837/5aac8275-f702-4c7e-bfa0-cb1a4ca7f8d7)
![屏幕截图 2024-01-22 132629](https://github.com/zhuzichu520/FluentUI/assets/22854837/204c0a71-a35e-4976-b62c-f30f1dc81691)

**Comment by zhuzichu520** [comment]
已修改再试试
https://github.com/zhuzichu520/FluentUI/commit/d6325b4f5baeafddcf5c570ccd772ff8faf1d1fa

**Comment by weypro** [comment]
好了
