### ISSUE TITLE
TableView列显隐

### ISSUE THREAD

**Issue by jlxzq** [zhuzichu520/FluentUI#410]
TableView会考虑扩展列显隐功能吗？因为我目前在写列显隐的时候遇到了一些困难，在表头和内容初始化之后，再去更改表头和内容的数据就会报错，大佬有什么好的实现思路吗？

**Comment by yanhuacuo** [comment]
列显隐，有其必要性。
比如 sqlite 数据库，它需要有一个「索引列」，在一些情形下，我们并不希望「索引列」被显示出来。
比如，从一个格式化的码表中，取其第一列与第二列的值拼接起来，作为新列用作「索引列」，这样做，有时是为了利用数据库录入时的自动滤重功能。
在 QTableView 中，有这样的属性：`ui->tableView->setColumnHidden(4,false);`
