### ISSUE TITLE
FluApp::navigate 单例模式

### ISSUE THREAD

**Issue by LiuPeiqiCN** [zhuzichu520/FluentUI#42]
example程序里左下角每点击一次“About”就会弹出一个新窗口，这个不太合理。FluApp::navigate如果可以增加一个是否启用单例模式参数会更好，每次最多只能有一个该界面被打开。如果重复打开，就激活之前的界面。

**Comment by zhuzichu520** [comment]
已经添加上了。FluWindowd新增launchMode枚举值，支持Standard、SingleTask、SingleInstance，具体使用方法看AboutPage

**Comment by zhuzichu520** [comment]
Standard默认每次都创建新窗口，SingleTask如果已经存在则激活窗口，SingleInstance如果存在则销毁新建窗口
