### ISSUE TITLE
用qt6.2.4编译源码时出现关于FluFramelessHelper的警告

### ISSUE THREAD

**Issue by 962412311** [zhuzichu520/FluentUI#421]
![image](https://github.com/zhuzichu520/FluentUI/assets/55896808/73d88938-35a8-4876-b107-96710935a607)

将FluentUI/src/FluFramelessHelper.h中对于FluFramelessHelper的声明添加一行代码后重新编译就不警告了：
![image](https://github.com/zhuzichu520/FluentUI/assets/55896808/41a75456-a13f-4b65-b43c-1ce218183594)

![image](https://github.com/zhuzichu520/FluentUI/assets/55896808/49b41939-6ade-43b9-b8b6-1d5a1f9b42fb)

附上cmake的结果，不用sudu时出现报错：
![image](https://github.com/zhuzichu520/FluentUI/assets/55896808/506dda97-2b58-4bdd-a003-4b9593b14174)

加上sudo后cmake无报错：
![image](https://github.com/zhuzichu520/FluentUI/assets/55896808/81c47229-f9ab-4282-a885-ee4463c2b2f5)

**Comment by 962412311** [comment]
我这个cmake需要sudo应该是因为我的qt6.2.4目录下都是root权限的文件

**Comment by zhuzichu520** [comment]
Q_INTERFACES(QQmlParserStatus) 已加上
