### ISSUE TITLE
能否维护个最新版FluentUI的脚手架template 工程  克隆之后开箱即用那种

### ISSUE THREAD

**Issue by cfscn** [zhuzichu520/FluentUI#434]
RT:  能否维护个最新版FluentUI的脚手架template 工程  克隆之后开箱即用那种
       目前需要根据examples 里面的代码去删减拼凑才能用.还得一边修改 一边调试.很是麻烦.

**Comment by suterberg** [comment]
那你得用widget编程，qml特性就是代码化的界面，免不了修改和调试，而且后端结合还要写中间层数据代理

**Comment by suterberg** [comment]
那你得用widget编程，qml特性就是代码化的界面，免不了修改和调试，而且后端结合还要写中间层数据代理
