### ISSUE TITLE
在禁用系统bar后启动时显示异常

### ISSUE THREAD

**Issue by MrChen-H** [zhuzichu520/FluentUI#436]
禁用系统bar后运行示例程序在启动时会出现整个界面异常闪烁,但是用鼠标调整一下窗口后就会恢复正常Debug Release 模式启动均有这个问题,在启用系统bar后就正常了 ,环境是Qt6.2 版本是1.69 win10 系统
![BugRes](https://github.com/zhuzichu520/FluentUI/assets/100182662/5cd9af70-1210-4309-a03c-8958373c9c60)

**Comment by zhuzichu520** [comment]
拉一下代码再试试~
https://github.com/zhuzichu520/FluentUI/commit/50f70711727169005a4bd9fb7b1add9855f432c7

**Comment by MrChen-H** [comment]
还是不行,而且更新代码后窗口的边缘检测也出问题了😭

**Comment by zhuzichu520** [comment]
嗯，边缘检测换成win32api实现了。很奇怪，我用win10虚拟机运行起来没啥问题。。你把这个运行日志给我看看
![1709007983780](https://github.com/zhuzichu520/FluentUI/assets/56627161/59e0e93a-9e38-4a31-adfd-77d99e873d8b)

**Comment by MrChen-H** [comment]
![bug](https://github.com/zhuzichu520/FluentUI/assets/100182662/00689143-869a-4208-8d95-e128254ab4fc)
报了一个看起来像是分辨率的警告

**Comment by MrChen-H** [comment]
这个显示器的分辨率是1920*1080的

**Comment by MrChen-H** [comment]
好的,辛苦大佬了,不过边缘检测的问题还是存在,在有两台显示器的情况下主显示器是正常的,但是当把程序移动到副显示器还是存在边缘检测异常的情况😨

**Comment by zhuzichu520** [comment]
额，献丑了，再试试~
https://github.com/zhuzichu520/FluentUI/commit/94c3ec83b3b69c82b8c8e9049767c3dfa89ea56a

**Comment by MrChen-H** [comment]
都好了,大佬nb,赞美大佬😘
