### ISSUE TITLE
大佬好，运行的时候回提示Unable to set geometry

### ISSUE THREAD

**Issue by zhangyebo1991** [zhuzichu520/FluentUI#440]
直观的结果就是设置x,y没有效果，一定会出现在中间
![QQ截图20240228155416](https://github.com/zhuzichu520/FluentUI/assets/8498452/fa828402-eb7d-4bff-afb8-31564ce47e0a)

**Comment by zhuzichu520** [comment]
FluWindow新增autoCenter属性，如何要想xy生效，可以将autoCenter改为false

**Comment by zhangyebo1991** [comment]
@zhuzichu520 感谢大佬，上面那个问题我更新后就解决了，不知道是不是我更新的有问题，我在调用FluTableView的时候，执行table_view.dataSource = data的时候，如果data数量大于1会报错，等于1或者0就不会，下面是我的代码
···
import QtQuick
import QtQuick.Controls
import QtQuick.Layouts
import QtQuick.Window
import FluentUI
import "./qml/pages"

/**
  * 1. FluSplitLayout 左右两侧，左侧是一个列表页，右侧是一个详情页
  * 2. 右侧是一个上下两层的column，上层展示设备的基本信息，导入一些配置等通用属性
  * 3. 下层主要展示设备的个性化配置信息
 **/

FluWindow {
    width: 1500
    height: 800
    x: 0
    y: 30
    visible: true
    title: qsTr("《说出来你可能不信》")
    autoCenter: false

    FluSplitLayout {
        id: test
        anchors.fill: parent
        orientation: Qt.Horizontal
        anchors {
            top: parent.top
            left: parent.left
            right: parent.right
            bottom: parent.bottom
            topMargin: 8
        }
        Item {
            implicitWidth: 180
            implicitHeight: 200
            Rectangle {
                color: "lightblue"
                width: 180
                height: parent.height
            }
            FluTableView {
                id: table_view
                horizonalHeaderVisible: true
                verticalHeaderVisible: false
                anchors {
                    left: parent.left
                    right: parent.right
                    top: parent.top
                    bottom: parent.bottom
                }
                columnSource: [
                    {
                        title: "设备列表",
                        dataIndex: "device",
                        width: 178,
                    }
                ]
            }
        }
        Item {
            implicitWidth: 100
            implicitHeight: 200
            Rectangle {
                color: "lightgreen"
                width: parent.width
                height: parent.height
            }

            T_DeviceDetail {

            }
        }
    }



    Component.onCompleted: {
        initTableView()
        table_view.enabled = false
    }

    function initTableView() {
        var data = []
        for (var i = 0; i < 20; i++) {
            data.push({
                device: "1" + i
            })
        }
        table_view.dataSource = data
    }
}

···
![QQ截图20240301155315](https://github.com/zhuzichu520/FluentUI/assets/8498452/62dd7b77-c692-4a01-8b6f-7619a7ad5b2d)

**Comment by zhuzichu520** [comment]
这行代码惹的祸，可以注释掉，目前FluTableView还在改造中。代码还没提交
https://github.com/zhuzichu520/FluentUI/blob/6a73ac97dfc70d09e860c53f42538287e90f2ee2/src/FluTableSortProxyModel.cpp#L11

**Comment by zhuzichu520** [comment]
已修改，再试试
https://github.com/zhuzichu520/FluentUI/commit/72b777dec3ffbbf88d0140b5d4ef5dd03c5b4f20

**Comment by zhangyebo1991** [comment]
@zhuzichu520 辛苦大佬了🙇‍♂️，已经可以了
