### ISSUE TITLE
关于FluTour是否可以引导home.qml中元素

### ISSUE THREAD

**Issue by qingyan520** [zhuzichu520/FluentUI#453]
博主您好，目前FlouTour只在MainWindow标题栏进行了使用，请问FluTour是否可以引导下面页面中的元素，比如home.qml中有个按钮，是否可以引导这个按钮，具体该如何使用呢

**Comment by zhuzichu520** [comment]
你可以在home.qml创建一个FluTour~

**Comment by qingyan520** [comment]
我的意思是先引导标题栏，然后再引导到home.qml中的元素，这种可以做到吗

**Comment by zhuzichu520** [comment]
可以的，在你的Home.qml 创建一个FluTour~，通过window可以拿到标题栏中的组件id。。

**Comment by qingyan520** [comment]
搞定了，感谢博主，请问就是有办法可以指引到左边导航栏中的某一个选项吗

**Comment by zhuzichu520** [comment]
左边导航本身就是个ListView，如果要定位到某一个选项，先要把它展开，让它可见，然后可以通过ListView的itemAtIndex方法，获取这个选项的id

**Comment by zhuzichu520** [comment]
FluNavigationView中的这个ListView没有暴露出来~你可以修改FluNavigationView，让ListView暴露出来

**Comment by qingyan520** [comment]
好的，了解了，感谢博主😄😄
