### ISSUE TITLE
全屏窗口导航闪烁的问题

### ISSUE THREAD

**Issue by zwh9527** [zhuzichu520/FluentUI#454]
设置了FullScreen的窗口使用导航打开另一个全屏的窗口，窗口会闪烁

**Comment by zhuzichu520** [comment]
如果你是用的Qt6.5+的话，可以把这行代码注释掉应该就好了
https://github.com/zhuzichu520/FluentUI/blob/eff9e385f53788301333c9b318af7445f4d06290/example/src/main.cpp#L57

**Comment by zhuzichu520** [comment]
还有一种方式就是不使用FullScreen，用下面这种也能实现全屏
```
   Component.onCompleted: {
        flags = flags | Qt.SplashScreen
        setGeometry(0,0,Screen.width,Screen.height)
    }
```

**Comment by zwh9527** [comment]
> 还有一种方式就是不使用FullScreen，用下面这种也能实现全屏
> 
> ```
>    Component.onCompleted: {
>         flags = flags | Qt.SplashScreen
>         setGeometry(0,0,Screen.width,Screen.height)
>     }
> ```

好的，谢谢大佬，我在论坛找到了另一个解决办法 QCoreApplication::setAttribute(Qt::AA_UseOpenGLES, true);
