### ISSUE TITLE
QCoreApplication::applicationFilePath: Please instantiate the QApplication object first

### ISSUE THREAD

**Issue by jackfahdin** [zhuzichu520/FluentUI#460]
git clone https://github.com/zhuzichu520/FluentUI.git

14:51:41: Starting D:\Program\QT\Github\FluentUI\bin\debug\example.exe...
QML debugging is enabled. Only use this in a safe environment.
QCoreApplication::applicationFilePath: Please instantiate the QApplication object first
14:51:42: D:\Program\QT\Github\FluentUI\bin\debug\example.exe 崩溃。

clone之后编译提示这个错误，请问有人知道是怎么回事吗
没看到有其他的错误提示了
qt6

**Comment by zhuzichu520** [comment]
额，是不是设置了Qt的环境变量？

**Comment by jackfahdin** [comment]
1.6.9.1176是可以编译的
今天最新的这个main是编译不了的
好奇怪，看不出来为啥

**Comment by zhuzichu520** [comment]
清理一下cmake的缓存再试试~

**Comment by jackfahdin** [comment]
试过了，还是不可以
我重新下载了一份，换了个工程目录作为一个新项目也还是编译不了

**Comment by jackfahdin** [comment]
我再想想其他的办法

找您确认一个问题
最新的main下载之后是直接编译的吧
不需要设置某个变量ON或者OFF吧

**Comment by zhuzichu520** [comment]
不需要~

**Comment by jackfahdin** [comment]
好像知道为啥了，
我的那个主机用的是QT6.8
换成qt6.6的现在可以了
