### ISSUE TITLE
GroupBox 黑色主题下显示不好看

### ISSUE THREAD

**Issue by jackfahdin** [zhuzichu520/FluentUI#461]
请问有计划加一下GroupBox的吗
黑色主题下，显示不正常
![image](https://github.com/zhuzichu520/FluentUI/assets/50285470/52c644e1-8860-4e9c-865e-742160842b1d)

**Comment by jackfahdin** [comment]
title的名字

**Comment by zhin2929** [comment]
看一下你的代码
