### ISSUE TITLE
上周的版本编译正常，今天的编译报错

### ISSUE THREAD

**Issue by Abelwlk** [zhuzichu520/FluentUI#463]
![image](https://github.com/zhuzichu520/FluentUI/assets/31944391/c75df254-7edf-4d85-9e4b-0b7e20ba9e23)

**Comment by Abelwlk** [comment]
![image](https://github.com/zhuzichu520/FluentUI/assets/31944391/7603d8a7-cb0b-4a5f-a5e8-a25c25425878)

**Comment by zhuzichu520** [comment]
看着好像是没有生成qm文件~确认一下是否生成了qm文件

**Comment by Abelwlk** [comment]
哎，公司加密软件给上锁了，怪不得生成失败
