### ISSUE TITLE
QT5.15.2+msvc2019_64编译成功，但无法运行

### ISSUE THREAD

**Issue by akjay** [zhuzichu520/FluentUI#465]
提示缺少DLL，打包Qt依赖后进调试直接崩溃

**Comment by zhuzichu520** [comment]
删除bin文件，重新编译试试

**Comment by akjay** [comment]
试过了，依然无法运行，我看项目描述里说有适用于qt5的分支，但是checkout没有看见，现在是都合并到master分支了吗？

**Comment by akjay** [comment]
另外，release中下载的版本可以安装运行

**Comment by zhuzichu520** [comment]
嗯嗯，qt5已合并到master

**Comment by akjay** [comment]
重新编译后运行example程序弹出提示如下![IMG_20240318_220534.jpg](https://github.com/zhuzichu520/FluentUI/assets/21979332/07e45b88-a634-4882-91e0-6c648acfedd8)

**Comment by akjay** [comment]
使用windeployqt打包，指定qml目录后可正常运行
windeployqt --qmldir dir example.exe
