### ISSUE TITLE
Qt6.4.3 _Qt_6_4_3_MinGW_64_bit-Debug 构建失败

### ISSUE THREAD

**Issue by Xminghaozz** [zhuzichu520/FluentUI#466]
![Uploading 1710723920811.png…]()
:-1: error: ninja: build stopped: subcommand failed. 
这个问题怎么解决啊，git clone下来后用QtCreator执行cmake，然后编译报这个错误

**Comment by Xminghaozz** [comment]
![1710724041511](https://github.com/zhuzichu520/FluentUI/assets/100988303/5d620687-1599-43b9-8ee8-3c2d072621d4)

**Comment by zhuzichu520** [comment]
看看编译的详细日志

**Comment by Xminghaozz** [comment]
![4f825b9c1f64c898b6b12688c90312d](https://github.com/zhuzichu520/FluentUI/assets/100988303/361ca304-4b0d-4d79-bd6b-d04f346902a6)

**Comment by zhuzichu520** [comment]
![1710727099787](https://github.com/zhuzichu520/FluentUI/assets/56627161/c92681fb-11d2-4bda-877a-04089b7195f7)
你把Qt Github 文件夹换成Qt_Github，文件夹不要有空格试试

**Comment by zhuzichu520** [comment]
看来CMAKE中要表示路径的变量还是要加个双引号~。。

**Comment by Xminghaozz** [comment]
谢谢大佬
