### ISSUE TITLE
ArchLinux 环境下编译失败

### ISSUE THREAD

**Issue by LuXts** [zhuzichu520/FluentUI#48]
如题。
## 环境
QMake version 3.1
Using Qt version 6.5.0 in /usr/lib
cmake version 3.26.3

## 原因
`QT_INSTALL_QML` 不知道为什么变成了 `/usr/lib/cmake/Qt6Core/../../../qml` 也就是 `/usr/qml` 

## 修复方式
手动修改 `src/CMakeLists.txt` 内 `set(QT_INSTALL_QML ${Qt6Core_DIR}/../../../qml)` 为 `set(QT_INSTALL_QML /usr/lib/qt6/qml)`

手动执行
```bash
mkdir build
cd build
cmake ../ -DCMAKE_BUILD_TYPE=Release
sudo make
```
> 为什么是手动呢？原因是因为我的 Qt Creator 不知道抽了什么疯，改 `src/CMakeLists.txt` 文件不生效。
> 另外求问 cmake 指定 QT 路径的方法。

## 建议
或许可以换一个方式探测 qml 路径？

**Comment by zhuzichu520** [comment]
额，是的，这个路径用cmake不太好找的，我前面找了半天，还要兼容各种平台。先写死吧，等有谁找到了提个合并请求。

**Comment by LuXts** [comment]
> 额，是的，这个路径用cmake不太好找的，我前面找了半天，还要兼容各种平台。先写死吧，等有谁找到了提个合并请求。

或许可以把 **构建** 和 **安装** 两个步骤分开？构建之后先不安装，让用户自己拷贝或者执行 `make install INSTALL_PATH` 。

如果 cmake 不好找就让用户自己输入吧（逃）

**Comment by zhuzichu520** [comment]
1.2.8版本已经换一种方式，不需要探测 qml 路径。
