### ISSUE TITLE
FluWindow 中如何使用 registerForPageResult？

### ISSUE THREAD

**Issue by OctalZero** [zhuzichu520/FluentUI#49]
请问如何在 FluWindow 中使用 registerForPageResult，以达到将打开的界面中填写的数据回传到主界面？
主界面是 FluWindow 的情况下，报错如下
![image](https://user-images.githubusercontent.com/75478802/231989312-326b3afc-6329-4e8e-b863-02c74af5c802.png)
博主给的模板是在 FluScrollablePage 下设置这个属性，使用正常，有方法能在 FluWindow 中使用吗？

**Comment by zhuzichu520** [comment]
registerForPageResult 这个方法就是FluWindow里面的。FluScrollablePage 中也是调用的FluWindow下的这个函数。能看看你的写法么？

**Comment by OctalZero** [comment]
写法：
在 FluWindow 里调用 registerForPageResult 初始化一个变量：
![image](https://user-images.githubusercontent.com/75478802/232036967-cbe82d6f-feec-4c07-8653-9736c91a3406.png)
App.qml中：
![image](https://user-images.githubusercontent.com/75478802/232037283-266f598c-8c56-469b-b2c7-32c479f0d7b8.png)
具体错误：调试时 FluRegister 构造的时候段错误了
![image](https://user-images.githubusercontent.com/75478802/232036774-3e4eb1bc-334b-4b2a-bde2-1a6528005466.png)

**Comment by zhuzichu520** [comment]
代码不是最新的。我看你FluApp还传了两个参数，最新代码已经把FluWindow重构了。可以拉下最新代码试试

**Comment by OctalZero** [comment]
> 代码不是最新的。我看你FluApp还传了两个参数，最新代码已经把FluWindow重构了。可以拉下最新代码试试

发现楼主更新了Qt5分支，刚刚已经更新到最新版了，但是楼主最新的这个 CodeExpander 的用法感觉很奇怪，没有看懂，不知道能不能解答下这个的作用，以及该如何使用
![image](https://user-images.githubusercontent.com/75478802/232091074-94a541cf-c917-46b6-accf-b4e56de0c6a9.png)

**Comment by OctalZero** [comment]
> 代码不是最新的。我看你FluApp还传了两个参数，最新代码已经把FluWindow重构了。可以拉下最新代码试试

感谢博主更新了qt5分支的代码，现在我已经移植好了最新代码，但是仍然跟原来一样的问题，不过我发现当我将 registerForPageResult 的变量名改为 loginPageRegister 时能够正常运行：
![image](https://user-images.githubusercontent.com/75478802/232107579-961770b2-fe50-48db-a570-c2205915a1f1.png)
下面是我在博主代码的 about 界面复现这个问题，当我申明非 loginPageRegister 的变量名，加载 about 页面时依然会异常结束：
![image](https://user-images.githubusercontent.com/75478802/232108583-30698edb-450b-44b4-a483-3628f8ed3bf2.png)
![image](https://user-images.githubusercontent.com/75478802/232109257-4763787c-8bf8-4254-b26b-4ff89b0ac2db.png)
![image](https://user-images.githubusercontent.com/75478802/232109085-52628523-ae7c-41a3-97b3-dec81efb2361.png)
请问博主该如何解决呢？

**Comment by zhuzichu520** [comment]
确实有这个问题，我研究下。。

**Comment by zhuzichu520** [comment]
重新编译一下就好了

**Comment by zhuzichu520** [comment]
构建->重新构建。试试

**Comment by zhuzichu520** [comment]
额，不对，是偶现的。。

**Comment by zhuzichu520** [comment]
再拉下qt5分支代码，已经没问题了。initWindow 比 registerForPageResult 执行晚一点导致的...

**Comment by OctalZero** [comment]
感谢博主！已解决！

**Comment by OctalZero** [comment]
注册界面：
虽然能够正常运行，但是 onResult 没能够被触发，请问博主该如何解决呢？通过打印输出，确认打开的界面onResult被触发，但是主界面未能触发返回的槽
![image](https://user-images.githubusercontent.com/75478802/232323707-5f8e4c73-673a-4bd0-afd0-bd7628c451a6.png)
回传数据：
![image](https://user-images.githubusercontent.com/75478802/232323729-0c9defe6-1910-498d-8caf-9447f4d1e929.png)
回传数据打印：
![image](https://user-images.githubusercontent.com/75478802/232323679-44819568-8e61-4996-aa25-c2a143e1cf9b.png)
