### ISSUE TITLE
FluNavigationView问题

### ISSUE THREAD

**Issue by wucw1225** [zhuzichu520/FluentUI#490]
1.7.5版本
用脚手架创建的项目
模仿example写MainWindow.qml
提示错误：2024/04/27 13:47:08.300[Warning][FluNavigationView.qml:1236][8204]:qrc:/qt/qml/FluentUI/Controls/FluNavigationView.qml:1236: TypeError: Cannot read property 'url' of undefined
2024/04/27 13:47:08.311[Warning][MainWindow.qml:110][8204]:qrc:/meta-meg/qml/window/MainWindow.qml:110: TypeError: Property 'getSearchData' of object [object Object] is not a function

**Comment by BlandAlpha** [comment]
你好，我也遇到了同样的问题，请问你是如何解决的？
