### ISSUE TITLE
Segoe_Fluent_Icons 在Def.h中定义？名称是根据微软文档手搓进去的吗？

### ISSUE THREAD

**Issue by gragonskies** [zhuzichu520/FluentUI#494]

**Comment by yanhuacuo** [comment]
是的，unicode点位

**Comment by zhuzichu520** [comment]
手搓是不可能手搓的，这么多，爬网页https://learn.microsoft.com/en-us/windows/apps/design/style/segoe-fluent-icons-font，然后解析一下。。。

**Comment by gragonskies** [comment]
找了很久，根本没有可以复制粘贴的位置，又不像fontawesome有文件。我说那么耐心呢，手搓。
