### ISSUE TITLE
请问pyqt可以使用吗？

### ISSUE THREAD

**Issue by Ephemeralwanning** [zhuzichu520/FluentUI#5]
请问pyqt可以使用吗？

**Comment by zhuzichu520** [comment]
目前还不行，后续再研究一波pyqt，py+qml，额没弄~

**Comment by parker-int64** [comment]
见这个[issue](https://github.com/zhuzichu520/FluentUI/issues/85#issuecomment-1537421515)，里面有一个测试的例程。

实际上对于Python而言，直接调用编译好的dll是可行的。编译完成的FluentUI文件夹和Fluentui.dll放在一起，使用PyQt6 / PySide6中的`engine.addImportPath(<包含有FluentUI文件夹的路径>)`函数，只要能找到FluentUI，正常情况下是能运行的。
