### ISSUE TITLE
根据wiki中的入门教程，编译提示 参数不足 咋搞

### ISSUE THREAD

**Issue by xxh396** [zhuzichu520/FluentUI#50]
根据wiki中的入门教程，编译提示 参数不足 咋搞
![image](https://user-images.githubusercontent.com/38549726/232000761-c85ec0c9-946c-44ea-87bd-a563bd9645a5.png)

**Comment by zhuzichu520** [comment]
很奇怪，清一清缓存在编译试试。没道理呀。。。。

**Comment by xxh396** [comment]
我清楚了还是不行欸，我用的qt6.4.3应该没影响把


小狂
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhuzichu520/FluentUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月14日(星期五) 下午5:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhuzichu520/FluentUI] 根据wiki中的入门教程，编译提示 参数不足 咋搞 (Issue #50)





 
很奇怪，清一清缓存在编译试试。没道理呀。。。。

**Comment by zhuzichu520** [comment]
看看你的study.pro文件

**Comment by xxh396** [comment]
好的 大佬




小狂
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhuzichu520/FluentUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月14日(星期五) 下午5:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhuzichu520/FluentUI] 根据wiki中的入门教程，编译提示 参数不足 咋搞 (Issue #50)





 
看看你的study.pro文件

**Comment by xxh396** [comment]
大佬能给我一份 wiki里的初始化工程源码吗，我参照下 是我哪里弄错了 谢谢啦



小狂
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhuzichu520/FluentUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月14日(星期五) 下午5:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhuzichu520/FluentUI] 根据wiki中的入门教程，编译提示 参数不足 咋搞 (Issue #50)





 
看看你的study.pro文件

**Comment by zhuzichu520** [comment]
已经提交到 https://github.com/zhuzichu520/FluentDemo

**Comment by xxh396** [comment]
谢谢 大佬


小狂
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhuzichu520/FluentUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月14日(星期五) 晚上8:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhuzichu520/FluentUI] 根据wiki中的入门教程，编译提示 参数不足 咋搞 (Issue #50)





 
已经提交到 https://github.com/zhuzichu520/FluentDemo
