### ISSUE TITLE
建议：FluWindows的onClosing事件不做操作

### ISSUE THREAD

**Issue by mentalfl0w** [zhuzichu520/FluentUI#52]
我的程序有个需求，是在点击关闭按钮后，让用户选择是否真正退出，但是Fluent UI库已经对onClosing事件做了响应，导致所有窗口资源在我进行操作前就已经被销毁，是否可以在库的层面上去除对这一事件的响应呢？
<img width="256" alt="image" src="https://user-images.githubusercontent.com/30333935/232223797-5d5b4044-40f7-4d2b-8ce4-2e793a567b96.png">

我的系统是macOS。

**Comment by zhuzichu520** [comment]
嗯，确实有这个问题，比如主窗口一般有托盘，然后点击关闭也不会把这个窗口杀掉。双击托盘还能激活。我研究下怎么改。。。

**Comment by zhuzichu520** [comment]
FluWindow新增了closeDestory属性，默认为true。可以在你的FluWindow窗口上改为false试试

**Comment by mentalfl0w** [comment]
> FluWindow新增了closeDestory属性，默认为true。可以在你的FluWindow窗口上改为false试试

目前测试的话，窗口确实不关闭了，但是也无法通过'Qt.quit()'或者'helper.destroyWindow()'来关闭窗口，导致整个程序只能隐藏无法退出
