### ISSUE TITLE
关于FluPivot的一点建议

### ISSUE THREAD

**Issue by parker-int64** [zhuzichu520/FluentUI#54]
# 组件名称： FluPivot，文件： `FluPivot.qml`

+ 问题描述1： `FluPivot`没有可供使用的`currentIndex`

在使用这种能够切换视图的组件的时候希望能够根据自己的想法切换`currentIndex`，此功能在`FluFlipView`中是提供了的。

解决办法：在`FluPivot.qml`加上如下属性

```QML

...
+ 12      property alias currentIndex: nav_list.currentIndex
...

```
+ 问题描述2： `FluPivot`组件高度（Height）问题

在布局中使用了

```QML
Layout.fillWidth: true
Layout.fillHeight: true
```
之后， 横向布局确实布满可用空间，但是纵向高度没占满导致`FluPivotItem`中的内容显示不全。

解决办法：手动设置了如下高度
```
height: 900
```

能够使内容显示出来，但是问题是两个或者多个`FluPivotItem`的高度全是手动设置的高度（900）了。

希望能达到的效果是根据页面纵向排列的内容多少而确认高度大小（目前想到的是根据`FluPivotItem`的高度来决定）

**Comment by zhuzichu520** [comment]
好，这个版本优化一下

**Comment by zhuzichu520** [comment]
问题2我还不太明白，FluPivotItem的高度是不需要设置。它的高度就是FluPivot的高度-50px。所以只要设置FluPivot的高度就行了，如果想所有子项的item高度位900px，那就直接设置FluPivot的高度为950px就够了

**Comment by parker-int64** [comment]
我有一个Item的高度是900，另一个Item高度600就够了；直接设置FluPivot高度的话，两个Item高度都一样了，显然另一个不需要这么高的话（高度为600的页面就可以滑动）

**Comment by zhuzichu520** [comment]
嗯嗯，明白了。可以FluPivotItem的contentItem中再嵌套一层600px的Item。

**Comment by zhuzichu520** [comment]
currentIndex已经新增
