### ISSUE TITLE
能否自定义全局字体

### ISSUE THREAD

**Issue by coconutzzZ336** [zhuzichu520/FluentUI#55]
以前的方法是在main函数中定义，不过好像只对.ui有效，对qml无效。
这个是以前的方法
```c++
QApplication a(argc, argv);
QFont f;
f.setFamily(QFontDatabase::applicationFontFamilies (QFontDatabase::addApplicationFont(":/res/fonts.ttf")).at(0));
a.setFont(f);
```

另外，`FluColorView` 的两个竖着的颜色滑动条拖动一点就会拖不动变成整个页面上下拖动了

**Comment by zhuzichu520** [comment]
可以的吧，不过还是不推荐全局设置，侵入性太高了。可以在Text用的时候添加font.family属性，如果用的地方多，那就封装一个Text

**Comment by zhuzichu520** [comment]
FluColorView 拖动事件冲突 main分支已经解决
