### ISSUE TITLE
How to hide Index in a FluTableView?

### ISSUE THREAD

**Issue by gaetandezeiraud** [zhuzichu520/FluentUI#557]
How to hide the index in a FluTableView?
For example here https://github.com/zhuzichu520/FluentUI/blob/main/example/qml/page/T_TableView.qml, How I can hide / remove the index column and start directly with the "Select All" one?

Thank you.

**Comment by ToMoree** [comment]
Set property verticalHeaderVisible false

**Comment by ToMoree** [comment]
> How to hide the index in a FluTableView? For example here https://github.com/zhuzichu520/FluentUI/blob/main/example/qml/page/T_TableView.qml, How I can hide / remove the index column and start directly with the "Select All" one?
> 
> Thank you.

Set property verticalHeaderVisible false.
