### ISSUE TITLE
按照Wiki操作但是提示Component is not ready

### ISSUE THREAD

**Issue by bz-2021** [zhuzichu520/FluentUI#56]
按照Wiki提示操作后，FluentDemo可以运行，但是example无法运行。
报错信息 `QQmlComponent: Component is not ready`。
是我哪一步错了吗？

**Comment by zhuzichu520** [comment]
额，问题解决了没？

**Comment by bz-2021** [comment]
未解决，依然报警告`:-1: warning: skipping module FluAutoSuggestBox`
共有十个类似的警告，不知道怎么办了，求教大佬。
