### ISSUE TITLE
Win11 Qt6.4.3   example运行崩溃

### ISSUE THREAD

**Issue by youbenbin** [zhuzichu520/FluentUI#57]
QQmlComponent: Component is not ready
运行不了

**Comment by zhuzichu520** [comment]
你用的Cmake还是qmake？如果是cmake的话换成qmake试试。

**Comment by satchelwu** [comment]
需要安装Qt5 compatible components

**Comment by itviewer** [comment]
[releases](https://github.com/zhuzichu520/FluentUI/releases) 的安装包应该是有问题
```
./example_1.2.6_ubuntu-20.04_Qt6.4.3.AppImage 
QQmlComponent: Component is not ready
Segmentation fault (core dumped)

```

**Comment by suterberg** [comment]
> 需要安装Qt5 compatible components

需要安装时勾选Qt 5 Compatibility Module 选项

**Comment by cworld1** [comment]
> 需要安装时勾选Qt 5 Compatibility Module 选项

还需要安装 Shader Tools。开发者的这个文档真该好好完善一下（
