### ISSUE TITLE
example process still existed  when closing the window

### ISSUE THREAD

**Issue by satchelwu** [zhuzichu520/FluentUI#64]
What a beautiful user interface ! but I met a problem. Here are the steps below. I found that process could not exit totally.
running....
![image](https://user-images.githubusercontent.com/6259509/233308076-f27befb1-2332-4eae-9541-be2d97051115.png)
close window
![image](https://user-images.githubusercontent.com/6259509/233308315-8b8d9838-53d2-4430-944c-6bb7ce119355.png)
process still existed
![image](https://user-images.githubusercontent.com/6259509/233308634-271ef077-bad7-4b94-bd8d-e457959697bb.png)

**Comment by satchelwu** [comment]
FluWindow.qml中加上
 onClosing:
        (event)=>{
            if(closeDestory){
                destoryWindow()
                **Qt.quit();**
            }else{
                visible = false
                event.accepted = false
            }
        }

**Comment by zhuzichu520** [comment]
嗯，因为main函数添加了`app.setQuitOnLastWindowClosed(false);`，点击关闭的话，会隐藏到托盘，不会真的退出，要退出可以右键托盘点击退出，托盘逻辑可以看MainPage.qml

**Comment by zhuzichu520** [comment]
如果要实现关闭窗口结束进程的话，可以将MainPage.qml中的FluWindow的closeDestory:false删掉

**Comment by satchelwu** [comment]
Thanks
