### ISSUE TITLE
能不能生成一个静态库方便作为第三方库使用呢？

### ISSUE THREAD

**Issue by yuewenma** [zhuzichu520/FluentUI#69]

**Comment by mentalfl0w** [comment]
将`FluentUI/src/FluentUI.pro`中的`CONFIG += sharedlib`改为`CONFIG += staticlib`再编译即可，静态库会出现在`FluentUI/bin`目录内。

**Comment by zhuzichu520** [comment]
已经在example添加如何使用静态库示例
