### ISSUE TITLE
为 QtQuick.Controls 中已有的控件定义主题

### ISSUE THREAD

**Issue by Reverier-Xu** [zhuzichu520/FluentUI#7]
您好，我看您的实现方式是基于Controls已有组件重新封装一份，在[Qt的文档](https://doc.qt.io/qt-6/qtquickcontrols2-customize.html#creating-a-custom-style)中有提到关于自定义主题的部分，实现成主题的话就可以直接调用Controls组件而不用重新命名了。我在想这样实现是不是会好一些？

**Comment by zhuzichu520** [comment]
这样的话感觉会弄混淆，比如我有很多个自定义按钮组件都是继承Button的，如果命名一样的话，都分不清用哪个Button了。import xxx as xxx，这样也不太方便

**Comment by Reverier-Xu** [comment]
> 这样的话感觉会弄混淆，比如我有很多个自定义按钮组件都是继承Button的，如果命名一样的话，都分不清用哪个Button了。import xxx as xxx，这样也不太方便

额外的组件可以另行提供？例如

```qml
import QtQuick.Controls
import QtQuick.Controls.Fluent // Button, ...
import FluentUI // IconButton, ColorPicker...

Item {
    ...
    Button { ... } // Button from QtQuick.Controls with Fluent style
    IconButton { ... } // customized IconButton from FluentUI
}
```

**Comment by Reverier-Xu** [comment]
我自己先fork一份试一试，合适的话给您提pr

**Comment by zhuzichu520** [comment]
嗯嗯

**Comment by zhuzichu520** [comment]
你说的是对的，我运行了一下Qt6.5.0报错了The current style does not support customizion of this control。Please customize a non-native style.....

**Comment by Reverier-Xu** [comment]
您更新项目的速度太快了 orz，有点跟不上重构，而且您实现的自定义组件越来越多了，似乎重构成主题也并不能优雅到哪里去，还是我新开一个项目，只做Controls中已有控件的主题插件吧，这样能更专注一些。

这个issue我先关了，等未来有机会能合并的话再从长计议。
