### ISSUE TITLE
按照教程重新构建后出现问题

### ISSUE THREAD

**Issue by ohyousayhi** [zhuzichu520/FluentUI#73]
我用的qt6.4.3+msvc2019 64bit
按照教程点击重新构建后出现下列问题：
file:///typelist.qml:3:1: error: module "FluentUI" is not installed
请问大佬如何解决？

**Comment by zhuzichu520** [comment]
额，不至于呐，看下Qt的安装目录下面 D:\Qt\6.4.3\msvc2019_64\qml  有FluentUI这个文件夹没？

**Comment by ohyousayhi** [comment]
大佬有这个文夹件，但是里面只有这两个文件
![image](https://user-images.githubusercontent.com/82577207/234024744-4d6f571c-7328-4c27-aa40-b6fa18255484.png)

**Comment by thhgg781213** [comment]
在 Qt 6.5.0 遇到相似的问题：
编译出的`plugins.qmltypes`一直无数据
```
running install to qtqml folder
Deleted file - D:\github\FluentUI\src\build-preset\plugins.qmltypes
qmlplugindump is deprecated.
Please declare your types using QML_ELEMENT and related macros.
Then utilize the build system to invoke qmltyperegistrar in order to
generate qmltypes files.
Error parsing dependencies file <outputOfQmlimportscanner>:illegal value at 0
failed to process output of qmlimportscanner
qmlimportscanner: No such file or directory: "qrc:/qt/qml"
QQmlComponent: Component is not ready
file:///typelist.qml:2:1: module "FluentUI" is not installed
The system cannot find the file specified.
```
![image](https://user-images.githubusercontent.com/63545780/234149267-586f1c6c-4e4b-4929-9a55-c97a7651405d.png)

**Comment by ohyousayhi** [comment]
大佬能否分享一下你安装qt时选择了哪些组件呢？我不知道是不是因为有的组件我没有勾选安装的原因

**Comment by zhuzichu520** [comment]
安装QT6的时候没有勾选Additional Libraries？或者再运行一遍。第一次运行会出现file:///typelist.qml:2:1: module "FluentUI" is not installed这个，再运行一下就好了。下个版本准备不用qmlplugindump.exe这种方式生成plugins.qmltypes。换成QML_ELEMENT......

**Comment by ohyousayhi** [comment]
additional libraries我都选了，再运行一遍会报这个file:///typelist.qml:3:1: error: module "FluentUI" plugin "FluentUI" not found
我看D:\Qt\6.4.3\msvc2019_64\qml 里的FluentUI还是只有之前那两个文件

**Comment by zhuzichu520** [comment]
切换到future分支试试~..future只支持Cmake了.已经改用QML_ELEMENT

**Comment by zhuzichu520** [comment]
已经同步至main分支
