### ISSUE TITLE
【Bug】最新的几个版本缺少包的版本号报错

### ISSUE THREAD

**Issue by OctalZero** [zhuzichu520/FluentUI#8]
源文件：
![image](https://user-images.githubusercontent.com/75478802/229325651-b78972d2-da43-4b1c-9a05-1ce5f1dab050.png)
报错：
![image](https://user-images.githubusercontent.com/75478802/229325607-7c79ced4-3637-4248-846d-9fd0eac6787f.png)

**Comment by zhuzichu520** [comment]
main分支用qt6编译，或者切换到qt5分之

**Comment by OctalZero** [comment]
问题已解决，感谢！作者是否考虑弄一个项目的讨论群呢？这样小的问题可以避免提issue。

**Comment by zhuzichu520** [comment]
目前还没打算，直接提issue吧，这样解决问题都有记录。方便以后查找
