### ISSUE TITLE
关于1.2.9在Qt6.5编译运行的问题

### ISSUE THREAD

**Issue by superlittlebinbin** [zhuzichu520/FluentUI#86]
系统版本：macOS 13.1
Qt:6.5.0
编译出来提示：
Attaching to the global shared memory
Previous owner timed out, taking ownership 13565284814143897104 -> 2687880225682888418
QQmlComponent: Component is not ready

**Comment by scx1125** [comment]
我也是，Our global IPC ID is  17527598157918703998
QQmlComponent: Component is not ready

**Comment by scx1125** [comment]
> 

安装Qt5 compatible components就可以了

**Comment by zhuzichu520** [comment]
1.3.2已经修改，main分支已经升级到6.5
