### ISSUE TITLE
SingleTask单例窗口可能存在一些问题

### ISSUE THREAD

**Issue by LiuPeiqiCN** [zhuzichu520/FluentUI#89]
因为经常需要在子窗口和父窗口来回切换，所以我把程序主界面设置为FluWindow.SingleTask的话，再在子界面调用FluApp.navigate("/")返回主窗口，但此时程序输出窗口时会报错，导致FluNavigationView的FluAutoSuggestBox失效：
```
qrc:/global/ItemsOriginal.qml: TypeError: Cannot read property 'getItems' of null)
```

原因可能是一些参数没传过去，比如下面的navigationView：
```
pragma Singleton

import QtQuick
import FluentUI

FluObject {

    property var navigationView

.....................
```

另一个问题，这个FluWindow.SingleTask在切换为原窗口的时候速度理应很快的，但实际感官并非如此，中间等待一段时间才转到原窗口，等待的时间就像这个界面重新打开了一样久。这个情况在界面里存在比较耗时的控件时很明显，比如Camera。

**Comment by zhuzichu520** [comment]
嗯，确实有问题，ItemsOriginal是个单例，然后新创建的窗口把navigationView的指针覆盖掉了
