### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by MyHubTo** [zhuzichu520/FluentUI#9]
做的挺好，不过建议优化一下FluArea,随窗口变化而自动调整组件位置；example 那个 Theming/Awesome,在最大窗口化时存在卡顿（可能与我电脑有关，组件太多绘制不过来）

**Comment by zhuzichu520** [comment]
嗯嗯，确实有点问题，FluArea升级到Qt6后不能自调调整组件位置了。。

**Comment by zhuzichu520** [comment]
FluArea 因为是在一个ColumnLayout下面，要用Layout.fillWidth或者Layout.preferredWidth设置宽。Awesome太卡可能是在Debug模式下，切换到Release模式下应该不会卡
