### ISSUE TITLE
qml无法加载库fluentuiplugin.dll：找不到指定的模块

### ISSUE THREAD

**Issue by Qujixiang** [zhuzichu520/FluentUI#91]
我将Release 1.2.9中的FluentUI放到了Qt的qml目录下，然后在项目中的qml文件中使用FluentUI时，它提示
`qrc:/number-group/App.qml:3:1: 无法加载库 H:\Programs\Qt\6.4.3\mingw_64\qml\FluentUI\fluentuiplugin.dll：找不到指定的模块。`

这种情况应该怎么办呢？（需要修改CMakeLists.txt文件吗？如果需要，请问怎么修改呢？）
以下是我的问题截图：
![issue](https://github.com/zhuzichu520/FluentUI/assets/45880913/968382a0-afde-47a4-81c9-fe346d0c592d)
![issue2](https://github.com/zhuzichu520/FluentUI/assets/45880913/41bf92b0-4a99-4f4e-aae6-f6598cb15e77)
![issue3](https://github.com/zhuzichu520/FluentUI/assets/45880913/5e32a73a-5dc9-473a-a8da-05ce53e1a3ac)
![issue4](https://github.com/zhuzichu520/FluentUI/assets/45880913/5fea8592-0065-4688-aeff-fbc24da389d4)

**Comment by runhey** [comment]
我碰到过这个问题，我把这个fluentuiplugin.dll扔到Dependencies分析发现找不到依赖的这个fluentui.dll
![image](https://github.com/zhuzichu520/FluentUI/assets/74492025/451222da-5ce9-4adc-bdde-ba2a6cad8f41)
所以你需要让程序知道有这个dll。
按照作者的demo，你可以放置在跟exe一样的路径
![image](https://github.com/zhuzichu520/FluentUI/assets/74492025/129af610-c76c-4b6a-b8b9-9a392e630fc0)

**Comment by runhey** [comment]
当然我是用的python来作为入口，所以我可以直接放置在python.exe目录下。对于如何指定fluentui.dll的路径我是不会的

**Comment by zhuzichu520** [comment]
少了fluentui.dll

**Comment by Qujixiang** [comment]
已解决，解决方案：将fluentui.dll放到Qt相应编译器下的动态链接库目录中
![solution](https://github.com/zhuzichu520/FluentUI/assets/45880913/05eeb496-0832-4822-bf21-c9d61521a596)
