### ISSUE TITLE
FluNavigationView可能存在多次创建同一页面的问题

### ISSUE THREAD

**Issue by mentalfl0w** [zhuzichu520/FluentUI#92]
在FluNavigationView组件上每次点击项目都会在StackView中push一次，只有点击返回按钮才会pop，切换至其他页面后再次点击已经push过的项目，FluNavigationView并不会从已创建的item中找出这一项目，而是push一个新的实例，这样感觉不太符合用户的使用习惯，理论上来说点击此前使用过的项目应该打开原有界面而不是新建一个。

**Comment by mentalfl0w** [comment]
看代码有点修改思路，等最近有空再去实现一下看看效果。

**Comment by zhuzichu520** [comment]
嗯，可以参考Android的Activity的4种启动模式来处理栈的页面逻辑
