### ISSUE TITLE
提示找不到指定模块

### ISSUE THREAD

**Issue by ohyousayhi** [zhuzichu520/FluentUI#96]
![image](https://github.com/zhuzichu520/FluentUI/assets/82577207/d416ab67-da4e-46ae-a7fd-979979d6c6ac)
纯小白，大佬可以问下这个是什么原因吗？
![image](https://github.com/zhuzichu520/FluentUI/assets/82577207/c9038b9c-f118-45e1-99f3-388e18184a7c)

**Comment by runhey** [comment]
[看这个issue](https://github.com/zhuzichu520/FluentUI/issues/91#issue-1702298036)

**Comment by ohyousayhi** [comment]
奥奥不好意思我没注意看打扰了，但我现在又遇到一个新问题，按照上面的解决方案后还是不能正常运行
![image](https://github.com/zhuzichu520/FluentUI/assets/82577207/8f4d820f-d1cf-41a9-84b2-f8501e6ab03a)
![image](https://github.com/zhuzichu520/FluentUI/assets/82577207/dfb78289-c52d-4c8e-b545-d17fbb3f810d)
![image](https://github.com/zhuzichu520/FluentUI/assets/82577207/bfe0880d-204a-468f-96ec-6d01c16b3f3b)

**Comment by runhey** [comment]
噢那我也不清楚了

**Comment by zhuzichu520** [comment]
重新拉去一下main代码，删除所有缓存。报错qt中qml路径下FluentUI。我在CMakeList.text中qt_add_qml_module新增了一个属性PLUGIN_TARGET。这样就不会生成fluentuiplugin.dll与fluentui.dll两个dll。只有一个fluentuiplugin.dll就能运行了

**Comment by ohyousayhi** [comment]
感谢大佬，已解决
