### ISSUE TITLE
:-1: error: ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by one-rabbit** [zhuzichu520/FluentUI#97]
编译的时候报错，环境 Qt6.5 + mingw64 + win; 没查到是cmake那个语句报了错，请教如何处理

**Comment by zhuzichu520** [comment]
不是用的Qt Creator打开的么？如果不是需要设置CMAKE_PREFIX_PATH

**Comment by one-rabbit** [comment]
我是用 qt creator 打开的

**Comment by one-rabbit** [comment]
经过测试目前 社区版跑起来了，企业版似乎有点问题

**Comment by one-rabbit** [comment]
经过测试是 cmd 没有找到，没啥问题

**Comment by mianshijiayou** [comment]
> 经过测试是 cmd 没有找到，没啥问题

请问你解决了吗？在下遇到同样的问题，windows下cmake编译qml都会有这个错误，linux下没有这个错误；如果解决了可以告知解决办法嘛

**Comment by one-rabbit** [comment]
解决了呀，你把cmd的权限给了就可以了

**Comment by mianshijiayou** [comment]
> 解决了呀，你把cmd的权限给了就可以了
cmd权限是指对应编译器命令提示符的运行管理员权限吗

**Comment by one-rabbit** [comment]
对的可以参考这个 https://blog.csdn.net/BiandanLoveyou/article/details/115339905；你可以直接看编译错误 




2318713786
***@***.***







                       
Original Email
                       
                     

Sender:"mianshijiayou"< ***@***.*** &gt;;

Sent Time:2023/5/18 16:16

To:"zhuzichu520/FluentUI"< ***@***.*** &gt;;

Cc recipient:"one-rabbit"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [zhuzichu520/FluentUI] :-1: error: ninja: build stopped:subcommand failed. (Issue #97)




  
解决了呀，你把cmd的权限给了就可以了
 cmd权限是指对应编译器命令提示符的运行管理员权限吗
  
&mdash;
